// ── Infrastructure file constants ────────────────────────────────────────

/** Files generated by the editor infrastructure (not user-created) */
export const INFRASTRUCTURE_FILES = new Set(['import-map.json', 'tsconfig.json', 'src/main.ts', 'src/uno.config.ts'])

/** Subset of infrastructure files shown in the "project" folder of the file tree */
export const REPL_BUILTIN_FILES = ['import-map.json', 'tsconfig.json'] as const

// ── Template files (matching Vuetify Play's v0 template) ────────────────

export function createMainTs (defaultTheme: 'light' | 'dark' = 'light'): string {
  return `import { createApp } from 'vue'
import App from './App.vue'
import { createThemePlugin } from '@vuetify/v0'
import './uno.config.ts'

const theme = createThemePlugin({
  default: '${defaultTheme}',
  themes: {
    light: {
      dark: false,
      colors: {
        'primary': '#3b82f6',
        'secondary': '#64748b',
        'accent': '#6366f1',
        'error': '#ef4444',
        'info': '#1867c0',
        'success': '#22c55e',
        'warning': '#f59e0b',
        'background': '#ffffff',
        'surface': '#ffffff',
        'surface-tint': '#f5f5f5',
        'surface-variant': '#e8e8e8',
        'divider': '#e0e0e0',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-accent': '#1a1a1a',
        'on-error': '#ffffff',
        'on-info': '#ffffff',
        'on-success': '#1a1a1a',
        'on-warning': '#1a1a1a',
        'on-background': '#212121',
        'on-surface': '#212121',
        'on-surface-variant': '#666666',
      },
    },
    dark: {
      dark: true,
      colors: {
        'primary': '#c4b5fd',
        'secondary': '#94a3b8',
        'accent': '#c084fc',
        'error': '#f87171',
        'info': '#38bdf8',
        'success': '#4ade80',
        'warning': '#fb923c',
        'background': '#121212',
        'surface': '#1a1a1a',
        'surface-tint': '#2a2a2a',
        'surface-variant': '#1e1e1e',
        'divider': '#404040',
        'on-primary': '#1a1a1a',
        'on-secondary': '#ffffff',
        'on-accent': '#ffffff',
        'on-error': '#1a1a1a',
        'on-info': '#1a1a1a',
        'on-success': '#1a1a1a',
        'on-warning': '#1a1a1a',
        'on-background': '#e0e0e0',
        'on-surface': '#e0e0e0',
        'on-surface-variant': '#a0a0a0',
      },
    },
  },
})

const app = createApp(App)
app.use(theme)
app.mount('#app')

// Reveal after UnoCSS runtime processes initial styles
requestAnimationFrame(() => {
  requestAnimationFrame(() => {
    document.getElementById('app')!.style.opacity = '1'
  })
})
`
}

export const UNO_CONFIG_TS = `// @ts-expect-error - esm.sh import
import defineConfig from 'https://esm.sh/@unocss/runtime'
// @ts-expect-error - esm.sh import
import presetWind4 from 'https://esm.sh/@unocss/preset-wind4'

defineConfig({
  defaults: {
    presets: [presetWind4()],
    theme: {
      colors: {
        'primary': 'var(--v0-primary)',
        'secondary': 'var(--v0-secondary)',
        'accent': 'var(--v0-accent)',
        'error': 'var(--v0-error)',
        'info': 'var(--v0-info)',
        'success': 'var(--v0-success)',
        'warning': 'var(--v0-warning)',
        'background': 'var(--v0-background)',
        'surface': 'var(--v0-surface)',
        'surface-tint': 'var(--v0-surface-tint)',
        'surface-variant': 'var(--v0-surface-variant)',
        'divider': 'var(--v0-divider)',
        'pre': 'var(--v0-pre)',
        'on-primary': 'var(--v0-on-primary)',
        'on-secondary': 'var(--v0-on-secondary)',
        'on-accent': 'var(--v0-on-accent)',
        'on-error': 'var(--v0-on-error)',
        'on-info': 'var(--v0-on-info)',
        'on-success': 'var(--v0-on-success)',
        'on-warning': 'var(--v0-on-warning)',
        'on-background': 'var(--v0-on-background)',
        'on-surface': 'var(--v0-on-surface)',
        'on-surface-variant': 'var(--v0-on-surface-variant)',
      },
      borderColor: {
        DEFAULT: 'var(--v0-divider)',
      },
    },
  },
})
`

// ── Default App.vue ─────────────────────────────────────────────────────

export const DEFAULT_CODE = `<script setup lang="ts">
  import { createStep } from '@vuetify/v0'
  import { computed } from 'vue'

  const steps = [
    { id: 'cart', label: 'Cart', icon: '1' },
    { id: 'shipping', label: 'Shipping', icon: '2' },
    { id: 'payment', label: 'Payment', icon: '3', disabled: true },
    { id: 'review', label: 'Review', icon: '4' },
    { id: 'confirm', label: 'Confirm', icon: '5' },
  ]

  const stepper = createStep()
  stepper.onboard(steps.map((s, i) => ({ id: s.id, value: i, disabled: s.disabled })))
  stepper.first()

  const currentIndex = computed(() => stepper.selectedIndex.value)
  const isFirst = computed(() => currentIndex.value === 0)
  const isLast = computed(() => currentIndex.value === stepper.size - 1)
</script>

<template>
  <div class="p-8 font-sans min-h-screen bg-background text-on-background">
    <!-- Stepper Track -->
    <div class="relative flex items-center justify-between mb-12">
      <!-- Background Line -->
      <div class="absolute top-5 left-0 right-0 h-0.5 bg-divider" />

      <!-- Progress Line -->
      <div
        class="absolute top-5 left-0 h-0.5 bg-primary transition-all duration-400"
        :style="{ width: (currentIndex / (steps.length - 1)) * 100 + '%' }"
      />

      <!-- Steps -->
      <div
        v-for="(step, i) in steps"
        :key="step.id"
        class="relative z-1 flex flex-col items-center cursor-pointer"
        @click="!step.disabled && stepper.select(step.id)"
      >
        <div
          class="w-10 h-10 rounded-full flex items-center justify-center text-sm font-semibold transition-all duration-300"
          :class="[
            i <= currentIndex ? 'bg-primary text-on-primary' : step.disabled ? 'bg-surface border-2 border-dashed border-divider' : 'bg-surface border-2 border-solid border-divider',
            i === currentIndex ? 'scale-115 shadow-[0_0_0_4px_rgba(59,130,246,0.2)]' : 'scale-90',
            step.disabled ? 'opacity-50' : '',
          ]"
        >
          <span v-if="i < currentIndex">&#10003;</span>
          <span v-else>{{ step.icon }}</span>
        </div>

        <span
          class="mt-2 text-xs font-medium"
          :class="[
            i === currentIndex ? 'text-primary' : 'text-on-surface-variant',
            step.disabled ? 'line-through opacity-50' : '',
          ]"
        >
          {{ step.label }}
        </span>
      </div>
    </div>

    <!-- Controls -->
    <div class="flex items-center justify-center gap-2">
      <button
        class="px-3 py-1.5 text-sm rounded border border-solid border-divider bg-surface cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
        :disabled="isFirst"
        @click="stepper.first()"
      >
        First
      </button>
      <button
        class="px-4 py-1.5 text-sm rounded border-none bg-surface-tint text-primary cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
        :disabled="isFirst"
        @click="stepper.prev()"
      >
        Prev
      </button>
      <button
        class="px-4 py-1.5 text-sm rounded border-none bg-primary text-on-primary cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
        :disabled="isLast"
        @click="stepper.next()"
      >
        Next
      </button>
      <button
        class="px-3 py-1.5 text-sm rounded border border-solid border-divider bg-surface cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
        :disabled="isLast"
        @click="stepper.last()"
      >
        Last
      </button>
    </div>

    <p class="mt-6 text-center text-xs text-on-surface-variant">
      Step {{ currentIndex + 1 }} of {{ stepper.size }} · Payment step is disabled (auto-skipped)
    </p>
  </div>
</template>
`
