// ── Infrastructure file constants ────────────────────────────────────────

/** Files generated by the editor infrastructure (not user-created) */
export const INFRASTRUCTURE_FILES = new Set(['import-map.json', 'tsconfig.json', 'src/main.ts', 'src/uno.config.ts'])

/** Subset of infrastructure files shown in the "project" folder of the file tree */
export const REPL_BUILTIN_FILES = ['import-map.json', 'tsconfig.json'] as const

// ── Template files (matching Vuetify Play's v0 template) ────────────────

export function createMainTs (defaultTheme: 'light' | 'dark' = 'light'): string {
  return `import { createApp } from 'vue'
import App from './App.vue'
import { createThemePlugin } from '@vuetify/v0'
import './uno.config.ts'

const theme = createThemePlugin({
  default: '${defaultTheme}',
  themes: {
    light: {
      dark: false,
      colors: {
        'primary': '#3b82f6',
        'secondary': '#64748b',
        'accent': '#6366f1',
        'error': '#ef4444',
        'info': '#1867c0',
        'success': '#22c55e',
        'warning': '#f59e0b',
        'background': '#ffffff',
        'surface': '#ffffff',
        'surface-tint': '#f5f5f5',
        'surface-variant': '#e8e8e8',
        'divider': '#e0e0e0',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-accent': '#1a1a1a',
        'on-error': '#ffffff',
        'on-info': '#ffffff',
        'on-success': '#1a1a1a',
        'on-warning': '#1a1a1a',
        'on-background': '#212121',
        'on-surface': '#212121',
        'on-surface-variant': '#666666',
      },
    },
    dark: {
      dark: true,
      colors: {
        'primary': '#c4b5fd',
        'secondary': '#94a3b8',
        'accent': '#c084fc',
        'error': '#f87171',
        'info': '#38bdf8',
        'success': '#4ade80',
        'warning': '#fb923c',
        'background': '#121212',
        'surface': '#1a1a1a',
        'surface-tint': '#2a2a2a',
        'surface-variant': '#1e1e1e',
        'divider': '#404040',
        'on-primary': '#1a1a1a',
        'on-secondary': '#ffffff',
        'on-accent': '#ffffff',
        'on-error': '#1a1a1a',
        'on-info': '#1a1a1a',
        'on-success': '#1a1a1a',
        'on-warning': '#1a1a1a',
        'on-background': '#e0e0e0',
        'on-surface': '#e0e0e0',
        'on-surface-variant': '#a0a0a0',
      },
    },
  },
})

const app = createApp(App)
app.use(theme)
app.mount('#app')
`
}

export const UNO_CONFIG_TS = `// @ts-expect-error - esm.sh import
import defineConfig from 'https://esm.sh/@unocss/runtime'
// @ts-expect-error - esm.sh import
import presetWind4 from 'https://esm.sh/@unocss/preset-wind4'

// Each recompile creates a fresh module instance with an empty internal style Map,
// so the previous runtime's <style> elements are abandoned in the DOM. Remove them
// before the new instance installs itself to prevent unbounded CSS rule accumulation.
document.querySelectorAll('[data-unocss-runtime-layer]').forEach(el => el.remove())

defineConfig({
  defaults: {
    presets: [presetWind4()],
    theme: {
      colors: {
        'primary': 'var(--v0-primary)',
        'secondary': 'var(--v0-secondary)',
        'accent': 'var(--v0-accent)',
        'error': 'var(--v0-error)',
        'info': 'var(--v0-info)',
        'success': 'var(--v0-success)',
        'warning': 'var(--v0-warning)',
        'background': 'var(--v0-background)',
        'surface': 'var(--v0-surface)',
        'surface-tint': 'var(--v0-surface-tint)',
        'surface-variant': 'var(--v0-surface-variant)',
        'divider': 'var(--v0-divider)',
        'pre': 'var(--v0-pre)',
        'on-primary': 'var(--v0-on-primary)',
        'on-secondary': 'var(--v0-on-secondary)',
        'on-accent': 'var(--v0-on-accent)',
        'on-error': 'var(--v0-on-error)',
        'on-info': 'var(--v0-on-info)',
        'on-success': 'var(--v0-on-success)',
        'on-warning': 'var(--v0-on-warning)',
        'on-background': 'var(--v0-on-background)',
        'on-surface': 'var(--v0-on-surface)',
        'on-surface-variant': 'var(--v0-on-surface-variant)',
      },
      borderColor: {
        DEFAULT: 'var(--v0-divider)',
      },
    },
  },
})
`

// ── Default App.vue ─────────────────────────────────────────────────────

export const DEFAULT_CODE = `<script lang="ts" setup>
  import { createSingle } from '@vuetify/v0'

  const single = createSingle({ mandatory: 'force' })

  single.onboard([
    { id: 'home', value: 'Home' },
    { id: 'profile', value: 'Profile' },
    { id: 'settings', value: 'Settings' },
  ])
</script>

<template>
  <div class="p-6">
    <div class="flex border-b border-divider mb-6">
      <button
        v-for="tab in single.values()"
        :key="tab.id"
        class="px-4 py-2 text-sm font-medium border-b-2 -mb-px transition-colors"
        :class="tab.isSelected.value
          ? 'text-primary border-primary'
          : 'text-on-surface-variant border-transparent hover:text-on-surface'"
        @click="tab.toggle()"
      >
        {{ tab.value }}
      </button>
    </div>

    <p class="text-sm text-on-surface-variant">
      Active tab: <strong class="text-on-surface">{{ single.selectedId.value }}</strong>
    </p>
  </div>
</template>
`
