// Utilities
import { strToU8, zipSync } from 'fflate'

// Engine
import {
  collectDependencies,
  generateDateStub,
  generateFiles,
  generateMainTs,
  needsDateStub,
} from './manifest'

export interface ZipManifest {
  selectedPlugins: Set<string>
  pluginConfig: Record<string, unknown>
  selectedComponents: Set<string>
  /** Composables pulled in by the resolver for the user's selection. */
  resolved?: string[]
}

// Pinned as a mutually compatible set and verified against a real
// `pnpm install && pnpm run build` of the generated starter.
const DEPS: Record<string, string> = {
  '@vuetify/v0': '^1.0.2',
  'vue': '^3.5.18',
}

const DEV_DEPS: Record<string, string> = {
  '@vitejs/plugin-vue': '^6.0.0',
  'typescript': '^5.9.2',
  'unocss': '^66.7.4',
  'vite': '^7.0.0',
  'vue-tsc': '^3.0.0',
}

function sort (deps: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(deps).toSorted(([a], [b]) => (a < b ? -1 : 1)))
}

function generatePackageJson (m: ZipManifest): string {
  const pkg = {
    name: 'my-v0-app',
    version: '0.0.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vue-tsc --noEmit && vite build',
      preview: 'vite preview',
    },
    dependencies: sort({ ...DEPS, ...collectDependencies(m.selectedPlugins, m.pluginConfig) }),
    devDependencies: sort(DEV_DEPS),
  }

  return JSON.stringify(pkg, null, 2) + '\n'
}

function generateViteConfig (): string {
  return `import { fileURLToPath, URL } from 'node:url'

import vue from '@vitejs/plugin-vue'
import UnoCSS from 'unocss/vite'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [
    vue(),
    UnoCSS(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})
`
}

function generateTsconfig (): string {
  return `{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "bundler",
    "lib": ["dom", "dom.iterable", "esnext"],
    "strict": true,
    "noEmit": true,
    "skipLibCheck": true,
    "verbatimModuleSyntax": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": ".",
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.vue"]
}
`
}

function generateEnvDts (): string {
  return `/// <reference types="vite/client" />
/// <reference types="unocss/vite" />
`
}

function generateUnoConfig (): string {
  return `import { defineConfig, presetWind4 } from 'unocss'

export default defineConfig({
  presets: [presetWind4()],
})
`
}

function generateIndexHtml (): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My v0 App</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`
}

function generateReadme (m: ZipManifest): string {
  const plugins = m.selectedPlugins.size
  const components = m.selectedComponents.size

  return `# my-v0-app

Generated by the v0 Framework Builder.

## What's inside

- ${plugins} plugin${plugins === 1 ? '' : 's'} wired in \`src/main.ts\`
- ${components} component${components === 1 ? '' : 's'} re-exported from \`src/framework.ts\`

## Quick start

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

## Your framework

\`src/framework.ts\` re-exports everything you selected. Import from there
rather than from \`@vuetify/v0\` directly, and add to it as your app grows.

## Editing the config

Plugin configuration lives in \`src/main.ts\`. Customize it there or run the
Builder again to regenerate.
`
}

function generateGitignore (): string {
  return `node_modules
dist
.DS_Store
*.log
`
}

// The zip and the playground ship the same demo sources — one generator, one
// set of files to keep correct.
export function generateSources (m: ZipManifest): Record<string, string> {
  const files = generateFiles({
    features: [...m.selectedPlugins, ...m.selectedComponents],
    resolved: m.resolved ?? [],
    adapters: {},
  })

  files['src/main.ts'] = generateMainTs(m.selectedPlugins, m.pluginConfig)

  if (needsDateStub(m.selectedPlugins, m.pluginConfig)) {
    files['src/adapters/date.ts'] = generateDateStub()
  }

  return files
}

export function generateZip (m: ZipManifest): Uint8Array {
  const files: Record<string, Uint8Array> = {
    'my-v0-app/package.json': strToU8(generatePackageJson(m)),
    'my-v0-app/vite.config.ts': strToU8(generateViteConfig()),
    'my-v0-app/tsconfig.json': strToU8(generateTsconfig()),
    'my-v0-app/uno.config.ts': strToU8(generateUnoConfig()),
    'my-v0-app/index.html': strToU8(generateIndexHtml()),
    'my-v0-app/README.md': strToU8(generateReadme(m)),
    'my-v0-app/.gitignore': strToU8(generateGitignore()),
    'my-v0-app/src/vite-env.d.ts': strToU8(generateEnvDts()),
  }

  for (const [path, source] of Object.entries(generateSources(m))) {
    files[`my-v0-app/${path}`] = strToU8(source)
  }

  return zipSync(files)
}

export function downloadZip (m: ZipManifest, filename = 'v0-starter.zip'): void {
  const bytes = generateZip(m)
  const blob = new Blob([bytes as BlobPart], { type: 'application/zip' })
  const url = URL.createObjectURL(blob)

  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.append(a)
  a.click()
  a.remove()

  URL.revokeObjectURL(url)
}
