// Utilities
import { strToU8, zipSync } from 'fflate'

// Engine
import { generateMainTs } from './manifest'

export interface ZipManifest {
  selectedPlugins: Set<string>
  pluginConfig: Record<string, unknown>
  selectedComponents: Set<string>
}

// Plugins that imply additional npm dependencies in the starter package.json
const PINIA_PLUGINS = new Set(['useStorage'])

function generatePackageJson (m: ZipManifest): string {
  const deps: Record<string, string> = {
    '@vuetify/v0': 'latest',
    'vue': '^3.5.0',
    'vue-router': '^4.4.0',
  }

  let needsPinia = false
  for (const id of m.selectedPlugins) {
    if (PINIA_PLUGINS.has(id)) needsPinia = true
  }

  if (needsPinia) deps.pinia = '^2.2.0'

  const devDeps: Record<string, string> = {
    '@vitejs/plugin-vue': '^5.1.0',
    'typescript': '^5.6.0',
    'unocss': '^0.65.0',
    'unplugin-vue-router': '^0.10.0',
    'vite': '^6.0.0',
    'vue-tsc': '^2.1.0',
  }

  const pkg = {
    name: 'my-v0-app',
    version: '0.0.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vue-tsc -b && vite build',
      preview: 'vite preview',
    },
    dependencies: deps,
    devDependencies: devDeps,
  }

  return JSON.stringify(pkg, null, 2) + '\n'
}

function generateViteConfig (): string {
  return `import { fileURLToPath, URL } from 'node:url'

import vue from '@vitejs/plugin-vue'
import UnocssVitePlugin from 'unocss/vite'
import VueRouter from 'unplugin-vue-router/vite'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [
    VueRouter(),
    vue(),
    UnocssVitePlugin(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})
`
}

function generateTsconfig (): string {
  return `{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "bundler",
    "lib": ["dom", "dom.iterable", "esnext"],
    "strict": true,
    "skipLibCheck": true,
    "verbatimModuleSyntax": true,
    "jsx": "preserve",
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["src/**/*.ts", "src/**/*.vue"]
}
`
}

function generateUnoConfig (): string {
  return `import { defineConfig, presetWind4 } from 'unocss'

export default defineConfig({
  presets: [presetWind4()],
})
`
}

function generateIndexHtml (): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My v0 App</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`
}

function generateAppVue (): string {
  return `<script setup lang="ts">
  import { RouterView } from 'vue-router'
</script>

<template>
  <RouterView />
</template>
`
}

function generateIndexPage (m: ZipManifest): string {
  const components = [...m.selectedComponents].slice(0, 3)

  if (components.length === 0) {
    return `<script setup lang="ts"></script>

<template>
  <div class="p-8">
    <h1 class="text-2xl font-bold">Welcome to your v0 app</h1>
    <p class="mt-2">Edit src/pages/index.vue to get started.</p>
  </div>
</template>
`
  }

  const importList = components.map(c => `  // import { ${c} } from '@vuetify/v0'`).join('\n')

  return `<script setup lang="ts">
${importList}
</script>

<template>
  <div class="p-8">
    <h1 class="text-2xl font-bold">Welcome to your v0 app</h1>
    <p class="mt-2">Your selected components are available from @vuetify/v0 — see imports above.</p>
  </div>
</template>
`
}

function generateReadme (m: ZipManifest): string {
  const pluginCount = m.selectedPlugins.size
  const componentCount = m.selectedComponents.size

  return `# my-v0-app

Generated by the v0 Framework Builder.

## What's inside

- ${pluginCount} plugin${pluginCount === 1 ? '' : 's'} wired in \`src/main.ts\`
- ${componentCount} component${componentCount === 1 ? '' : 's'} available from \`@vuetify/v0\`

## Quick start

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

## Editing the config

Your plugin configurations live in \`src/main.ts\`. Customize them
there or use the Builder again to regenerate.
`
}

function generateGitignore (): string {
  return `node_modules
dist
.DS_Store
*.log
`
}

export function generateZip (m: ZipManifest): Uint8Array {
  const files: Record<string, Uint8Array> = {
    'my-v0-app/package.json': strToU8(generatePackageJson(m)),
    'my-v0-app/vite.config.ts': strToU8(generateViteConfig()),
    'my-v0-app/tsconfig.json': strToU8(generateTsconfig()),
    'my-v0-app/uno.config.ts': strToU8(generateUnoConfig()),
    'my-v0-app/index.html': strToU8(generateIndexHtml()),
    'my-v0-app/README.md': strToU8(generateReadme(m)),
    'my-v0-app/.gitignore': strToU8(generateGitignore()),
    'my-v0-app/src/main.ts': strToU8(generateMainTs(m.selectedPlugins, m.pluginConfig)),
    'my-v0-app/src/App.vue': strToU8(generateAppVue()),
    'my-v0-app/src/pages/index.vue': strToU8(generateIndexPage(m)),
  }

  return zipSync(files)
}

export function downloadZip (m: ZipManifest, filename = 'v0-starter.zip'): void {
  const bytes = generateZip(m)
  const blob = new Blob([bytes as BlobPart], { type: 'application/zip' })
  const url = URL.createObjectURL(blob)

  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.append(a)
  a.click()
  a.remove()

  URL.revokeObjectURL(url)
}
