packages:
  - packages/*
  - apps/*
  - playground

autoInstallPeers: true

catalog:
  '@tsconfig/node22': ^22.0.2
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  unocss: ^66.5.1
  typescript: 5.8.3
  unplugin-vue: ^7.0.1
  unplugin-vue-components: ^29.0.0
  vite: npm:rolldown-vite@^7.1.8
  vue: ^3.5.21
  tsdown: ^0.14.2

catalogMode: 'strict'

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  vite: npm:rolldown-vite@^7.1.8
