packages:
  - packages/*
  - apps/*
  - playground

catalog:
  vue: ^3.5.17
  vite: npm:rolldown-vite@^7.0.3
  typescript: ^5.8.3
  '@vue/tsconfig': ^0.7.0
  '@tsconfig/node22': ^22.0.2
  unplugin-vue: ^6.2.0
  '@vue/test-utils': ^2.4.6

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  '@storybook/vue3-vite>vite': ^7.0.0
  '@storybook/builder-vite>vite': ^7.0.0
  vite: npm:rolldown-vite@^7.0.3

autoInstallPeers: true