packages:
  - packages/*
  - apps/*
  - playground

autoInstallPeers: true

catalog:
  '@tsconfig/node22': ^22.0.2
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  unocss: ^66.4.2
  typescript: 5.8.3
  unplugin-vue: ^6.2.0
  unplugin-vue-components: ^29.0.0
  vite: npm:rolldown-vite@^7.1.0
  vue: ^3.5.17
  tsdown: ^0.14.2

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  '@storybook/builder-vite>vite': ^7.0.0
  '@storybook/vue3-vite>vite': ^7.0.0
  vite: npm:rolldown-vite@^7.1.0
