packages:
  - packages/*
  - apps/*
  - playground

autoInstallPeers: true

catalog:
  '@mdi/js': npm:mdi-js-es@7.4.47
  '@octokit/core': ^7.0.3
  '@octokit/openapi-types': ^25.1.0
  '@shikijs/langs': ^3.12.2
  '@shikijs/markdown-it': ^3.12.2
  '@shikijs/themes': ^3.12.2
  '@storybook/vue3-vite': ^9.1.5
  '@tsconfig/node22': ^22.0.2
  '@types/markdown-it-attrs': ^4.1.3
  '@types/node': ^24.7.2
  '@unocss/reset': ^66.5.1
  '@vitest/coverage-v8': 3.2.4
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  '@vuetify/one': ^2.4.0
  bumpp: ^10.3.1
  eslint: ^9.37.0
  eslint-config-vuetify: 4.1.0-0
  eslint-plugin-storybook: ^9.1.10
  eslint-plugin-vuejs-accessibility: ^2.4.1
  happy-dom: ^18.0.1
  knip: ^5.65.0
  markdown-it-anchor: ^9.2.0
  markdown-it-attrs: ^4.3.1
  mermaid: ^11.11.0
  pinia: ^3.0.3
  rollup-plugin-sass: ^1.15.3
  sass: ^1.92.1
  sass-embedded: ^1.92.1
  sherif: ^1.6.1
  shiki: ^3.12.2
  storybook: ^9.1.10
  tsdown: ^0.14.2
  typescript: 5.8.3
  unocss: ^66.5.1
  unplugin-auto-import: ^19.3.0
  unplugin-vue: ^7.0.1
  unplugin-vue-components: ^29.0.0
  unplugin-vue-markdown: ^29.1.0
  unplugin-vue-router: ^0.15.0
  vite: npm:rolldown-vite@^7.1.8
  vite-plugin-vue-layouts-next: ^1.0.0
  vite-ssg: ^28.1.0
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-router: ^4.5.1
  vue-tsc: ^3.1.1

catalogMode: strict

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  '@storybook/builder-vite>vite': ^7.0.0
  '@storybook/vue3-vite>vite': ^7.0.0
  vite: npm:rolldown-vite@^7.1.8
