/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/api/': RouteRecordInfo<
      '/api/',
      '/api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api/[name]': RouteRecordInfo<
      '/api/[name]',
      '/api/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/components/': RouteRecordInfo<
      '/components/',
      '/components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/disclosure/dialog': RouteRecordInfo<
      '/components/disclosure/dialog',
      '/components/disclosure/dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/disclosure/expansion-panel': RouteRecordInfo<
      '/components/disclosure/expansion-panel',
      '/components/disclosure/expansion-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/disclosure/popover': RouteRecordInfo<
      '/components/disclosure/popover',
      '/components/disclosure/popover',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/primitives/atom': RouteRecordInfo<
      '/components/primitives/atom',
      '/components/primitives/atom',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/providers/group': RouteRecordInfo<
      '/components/providers/group',
      '/components/providers/group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/providers/selection': RouteRecordInfo<
      '/components/providers/selection',
      '/components/providers/selection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/providers/single': RouteRecordInfo<
      '/components/providers/single',
      '/components/providers/single',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/providers/step': RouteRecordInfo<
      '/components/providers/step',
      '/components/providers/step',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/semantic/avatar': RouteRecordInfo<
      '/components/semantic/avatar',
      '/components/semantic/avatar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/semantic/pagination': RouteRecordInfo<
      '/components/semantic/pagination',
      '/components/semantic/pagination',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/': RouteRecordInfo<
      '/composables/',
      '/composables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/forms/create-form': RouteRecordInfo<
      '/composables/forms/create-form',
      '/composables/forms/create-form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/foundation/create-context': RouteRecordInfo<
      '/composables/foundation/create-context',
      '/composables/foundation/create-context',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/foundation/create-plugin': RouteRecordInfo<
      '/composables/foundation/create-plugin',
      '/composables/foundation/create-plugin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/foundation/create-trinity': RouteRecordInfo<
      '/composables/foundation/create-trinity',
      '/composables/foundation/create-trinity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/plugins/use-breakpoints': RouteRecordInfo<
      '/composables/plugins/use-breakpoints',
      '/composables/plugins/use-breakpoints',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/plugins/use-date': RouteRecordInfo<
      '/composables/plugins/use-date',
      '/composables/plugins/use-date',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/plugins/use-features': RouteRecordInfo<
      '/composables/plugins/use-features',
      '/composables/plugins/use-features',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/plugins/use-hydration': RouteRecordInfo<
      '/composables/plugins/use-hydration',
      '/composables/plugins/use-hydration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/plugins/use-locale': RouteRecordInfo<
      '/composables/plugins/use-locale',
      '/composables/plugins/use-locale',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/plugins/use-logger': RouteRecordInfo<
      '/composables/plugins/use-logger',
      '/composables/plugins/use-logger',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/plugins/use-permissions': RouteRecordInfo<
      '/composables/plugins/use-permissions',
      '/composables/plugins/use-permissions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/plugins/use-storage': RouteRecordInfo<
      '/composables/plugins/use-storage',
      '/composables/plugins/use-storage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/plugins/use-theme': RouteRecordInfo<
      '/composables/plugins/use-theme',
      '/composables/plugins/use-theme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/reactivity/use-proxy-model': RouteRecordInfo<
      '/composables/reactivity/use-proxy-model',
      '/composables/reactivity/use-proxy-model',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/reactivity/use-proxy-registry': RouteRecordInfo<
      '/composables/reactivity/use-proxy-registry',
      '/composables/reactivity/use-proxy-registry',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/registration/create-queue': RouteRecordInfo<
      '/composables/registration/create-queue',
      '/composables/registration/create-queue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/registration/create-registry': RouteRecordInfo<
      '/composables/registration/create-registry',
      '/composables/registration/create-registry',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/registration/create-timeline': RouteRecordInfo<
      '/composables/registration/create-timeline',
      '/composables/registration/create-timeline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/registration/create-tokens': RouteRecordInfo<
      '/composables/registration/create-tokens',
      '/composables/registration/create-tokens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/selection/create-group': RouteRecordInfo<
      '/composables/selection/create-group',
      '/composables/selection/create-group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/selection/create-selection': RouteRecordInfo<
      '/composables/selection/create-selection',
      '/composables/selection/create-selection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/selection/create-single': RouteRecordInfo<
      '/composables/selection/create-single',
      '/composables/selection/create-single',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/selection/create-step': RouteRecordInfo<
      '/composables/selection/create-step',
      '/composables/selection/create-step',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/system/use-click-outside': RouteRecordInfo<
      '/composables/system/use-click-outside',
      '/composables/system/use-click-outside',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/system/use-event-listener': RouteRecordInfo<
      '/composables/system/use-event-listener',
      '/composables/system/use-event-listener',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/system/use-hotkey': RouteRecordInfo<
      '/composables/system/use-hotkey',
      '/composables/system/use-hotkey',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/system/use-intersection-observer': RouteRecordInfo<
      '/composables/system/use-intersection-observer',
      '/composables/system/use-intersection-observer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/system/use-media-query': RouteRecordInfo<
      '/composables/system/use-media-query',
      '/composables/system/use-media-query',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/system/use-mutation-observer': RouteRecordInfo<
      '/composables/system/use-mutation-observer',
      '/composables/system/use-mutation-observer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/system/use-resize-observer': RouteRecordInfo<
      '/composables/system/use-resize-observer',
      '/composables/system/use-resize-observer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/system/use-toggle-scope': RouteRecordInfo<
      '/composables/system/use-toggle-scope',
      '/composables/system/use-toggle-scope',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/transformers/to-array': RouteRecordInfo<
      '/composables/transformers/to-array',
      '/composables/transformers/to-array',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/transformers/to-reactive': RouteRecordInfo<
      '/composables/transformers/to-reactive',
      '/composables/transformers/to-reactive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/utilities/use-filter': RouteRecordInfo<
      '/composables/utilities/use-filter',
      '/composables/utilities/use-filter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/utilities/use-overflow': RouteRecordInfo<
      '/composables/utilities/use-overflow',
      '/composables/utilities/use-overflow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/utilities/use-pagination': RouteRecordInfo<
      '/composables/utilities/use-pagination',
      '/composables/utilities/use-pagination',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/utilities/use-virtual': RouteRecordInfo<
      '/composables/utilities/use-virtual',
      '/composables/utilities/use-virtual',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/': RouteRecordInfo<
      '/guide/',
      '/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/accessibility': RouteRecordInfo<
      '/guide/accessibility',
      '/guide/accessibility',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/ai-tools': RouteRecordInfo<
      '/guide/ai-tools',
      '/guide/ai-tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/building-docs': RouteRecordInfo<
      '/guide/building-docs',
      '/guide/building-docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/components': RouteRecordInfo<
      '/guide/components',
      '/guide/components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/composables': RouteRecordInfo<
      '/guide/composables',
      '/guide/composables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/core': RouteRecordInfo<
      '/guide/core',
      '/guide/core',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/nuxt': RouteRecordInfo<
      '/guide/nuxt',
      '/guide/nuxt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/plugins': RouteRecordInfo<
      '/guide/plugins',
      '/guide/plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/theming': RouteRecordInfo<
      '/guide/theming',
      '/guide/theming',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/using-the-docs': RouteRecordInfo<
      '/guide/using-the-docs',
      '/guide/using-the-docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/utilities': RouteRecordInfo<
      '/guide/utilities',
      '/guide/utilities',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/vuetify-mcp': RouteRecordInfo<
      '/guide/vuetify-mcp',
      '/guide/vuetify-mcp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/introduction/contributing': RouteRecordInfo<
      '/introduction/contributing',
      '/introduction/contributing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/introduction/frequently-asked': RouteRecordInfo<
      '/introduction/frequently-asked',
      '/introduction/frequently-asked',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/introduction/getting-started': RouteRecordInfo<
      '/introduction/getting-started',
      '/introduction/getting-started',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/releases': RouteRecordInfo<
      '/releases',
      '/releases',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/roadmap': RouteRecordInfo<
      '/roadmap',
      '/roadmap',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/storybook/': RouteRecordInfo<
      '/storybook/',
      '/storybook',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/storybook.view': RouteRecordInfo<
      '/storybook.view',
      '/storybook/view',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/api/index.md': {
      routes:
        | '/api/'
      views:
        | never
    }
    'src/pages/api/[name].vue': {
      routes:
        | '/api/[name]'
      views:
        | never
    }
    'src/pages/components/index.md': {
      routes:
        | '/components/'
      views:
        | never
    }
    'src/pages/components/disclosure/dialog.md': {
      routes:
        | '/components/disclosure/dialog'
      views:
        | never
    }
    'src/pages/components/disclosure/expansion-panel.md': {
      routes:
        | '/components/disclosure/expansion-panel'
      views:
        | never
    }
    'src/pages/components/disclosure/popover.md': {
      routes:
        | '/components/disclosure/popover'
      views:
        | never
    }
    'src/pages/components/primitives/atom.md': {
      routes:
        | '/components/primitives/atom'
      views:
        | never
    }
    'src/pages/components/providers/group.md': {
      routes:
        | '/components/providers/group'
      views:
        | never
    }
    'src/pages/components/providers/selection.md': {
      routes:
        | '/components/providers/selection'
      views:
        | never
    }
    'src/pages/components/providers/single.md': {
      routes:
        | '/components/providers/single'
      views:
        | never
    }
    'src/pages/components/providers/step.md': {
      routes:
        | '/components/providers/step'
      views:
        | never
    }
    'src/pages/components/semantic/avatar.md': {
      routes:
        | '/components/semantic/avatar'
      views:
        | never
    }
    'src/pages/components/semantic/pagination.md': {
      routes:
        | '/components/semantic/pagination'
      views:
        | never
    }
    'src/pages/composables/index.md': {
      routes:
        | '/composables/'
      views:
        | never
    }
    'src/pages/composables/forms/create-form.md': {
      routes:
        | '/composables/forms/create-form'
      views:
        | never
    }
    'src/pages/composables/foundation/create-context.md': {
      routes:
        | '/composables/foundation/create-context'
      views:
        | never
    }
    'src/pages/composables/foundation/create-plugin.md': {
      routes:
        | '/composables/foundation/create-plugin'
      views:
        | never
    }
    'src/pages/composables/foundation/create-trinity.md': {
      routes:
        | '/composables/foundation/create-trinity'
      views:
        | never
    }
    'src/pages/composables/plugins/use-breakpoints.md': {
      routes:
        | '/composables/plugins/use-breakpoints'
      views:
        | never
    }
    'src/pages/composables/plugins/use-date.md': {
      routes:
        | '/composables/plugins/use-date'
      views:
        | never
    }
    'src/pages/composables/plugins/use-features.md': {
      routes:
        | '/composables/plugins/use-features'
      views:
        | never
    }
    'src/pages/composables/plugins/use-hydration.md': {
      routes:
        | '/composables/plugins/use-hydration'
      views:
        | never
    }
    'src/pages/composables/plugins/use-locale.md': {
      routes:
        | '/composables/plugins/use-locale'
      views:
        | never
    }
    'src/pages/composables/plugins/use-logger.md': {
      routes:
        | '/composables/plugins/use-logger'
      views:
        | never
    }
    'src/pages/composables/plugins/use-permissions.md': {
      routes:
        | '/composables/plugins/use-permissions'
      views:
        | never
    }
    'src/pages/composables/plugins/use-storage.md': {
      routes:
        | '/composables/plugins/use-storage'
      views:
        | never
    }
    'src/pages/composables/plugins/use-theme.md': {
      routes:
        | '/composables/plugins/use-theme'
      views:
        | never
    }
    'src/pages/composables/reactivity/use-proxy-model.md': {
      routes:
        | '/composables/reactivity/use-proxy-model'
      views:
        | never
    }
    'src/pages/composables/reactivity/use-proxy-registry.md': {
      routes:
        | '/composables/reactivity/use-proxy-registry'
      views:
        | never
    }
    'src/pages/composables/registration/create-queue.md': {
      routes:
        | '/composables/registration/create-queue'
      views:
        | never
    }
    'src/pages/composables/registration/create-registry.md': {
      routes:
        | '/composables/registration/create-registry'
      views:
        | never
    }
    'src/pages/composables/registration/create-timeline.md': {
      routes:
        | '/composables/registration/create-timeline'
      views:
        | never
    }
    'src/pages/composables/registration/create-tokens.md': {
      routes:
        | '/composables/registration/create-tokens'
      views:
        | never
    }
    'src/pages/composables/selection/create-group.md': {
      routes:
        | '/composables/selection/create-group'
      views:
        | never
    }
    'src/pages/composables/selection/create-selection.md': {
      routes:
        | '/composables/selection/create-selection'
      views:
        | never
    }
    'src/pages/composables/selection/create-single.md': {
      routes:
        | '/composables/selection/create-single'
      views:
        | never
    }
    'src/pages/composables/selection/create-step.md': {
      routes:
        | '/composables/selection/create-step'
      views:
        | never
    }
    'src/pages/composables/system/use-click-outside.md': {
      routes:
        | '/composables/system/use-click-outside'
      views:
        | never
    }
    'src/pages/composables/system/use-event-listener.md': {
      routes:
        | '/composables/system/use-event-listener'
      views:
        | never
    }
    'src/pages/composables/system/use-hotkey.md': {
      routes:
        | '/composables/system/use-hotkey'
      views:
        | never
    }
    'src/pages/composables/system/use-intersection-observer.md': {
      routes:
        | '/composables/system/use-intersection-observer'
      views:
        | never
    }
    'src/pages/composables/system/use-media-query.md': {
      routes:
        | '/composables/system/use-media-query'
      views:
        | never
    }
    'src/pages/composables/system/use-mutation-observer.md': {
      routes:
        | '/composables/system/use-mutation-observer'
      views:
        | never
    }
    'src/pages/composables/system/use-resize-observer.md': {
      routes:
        | '/composables/system/use-resize-observer'
      views:
        | never
    }
    'src/pages/composables/system/use-toggle-scope.md': {
      routes:
        | '/composables/system/use-toggle-scope'
      views:
        | never
    }
    'src/pages/composables/transformers/to-array.md': {
      routes:
        | '/composables/transformers/to-array'
      views:
        | never
    }
    'src/pages/composables/transformers/to-reactive.md': {
      routes:
        | '/composables/transformers/to-reactive'
      views:
        | never
    }
    'src/pages/composables/utilities/use-filter.md': {
      routes:
        | '/composables/utilities/use-filter'
      views:
        | never
    }
    'src/pages/composables/utilities/use-overflow.md': {
      routes:
        | '/composables/utilities/use-overflow'
      views:
        | never
    }
    'src/pages/composables/utilities/use-pagination.md': {
      routes:
        | '/composables/utilities/use-pagination'
      views:
        | never
    }
    'src/pages/composables/utilities/use-virtual.md': {
      routes:
        | '/composables/utilities/use-virtual'
      views:
        | never
    }
    'src/pages/guide/index.md': {
      routes:
        | '/guide/'
      views:
        | never
    }
    'src/pages/guide/accessibility.md': {
      routes:
        | '/guide/accessibility'
      views:
        | never
    }
    'src/pages/guide/ai-tools.md': {
      routes:
        | '/guide/ai-tools'
      views:
        | never
    }
    'src/pages/guide/building-docs.md': {
      routes:
        | '/guide/building-docs'
      views:
        | never
    }
    'src/pages/guide/components.md': {
      routes:
        | '/guide/components'
      views:
        | never
    }
    'src/pages/guide/composables.md': {
      routes:
        | '/guide/composables'
      views:
        | never
    }
    'src/pages/guide/core.md': {
      routes:
        | '/guide/core'
      views:
        | never
    }
    'src/pages/guide/nuxt.md': {
      routes:
        | '/guide/nuxt'
      views:
        | never
    }
    'src/pages/guide/plugins.md': {
      routes:
        | '/guide/plugins'
      views:
        | never
    }
    'src/pages/guide/theming.md': {
      routes:
        | '/guide/theming'
      views:
        | never
    }
    'src/pages/guide/using-the-docs.md': {
      routes:
        | '/guide/using-the-docs'
      views:
        | never
    }
    'src/pages/guide/utilities.md': {
      routes:
        | '/guide/utilities'
      views:
        | never
    }
    'src/pages/guide/vuetify-mcp.md': {
      routes:
        | '/guide/vuetify-mcp'
      views:
        | never
    }
    'src/pages/introduction/contributing.md': {
      routes:
        | '/introduction/contributing'
      views:
        | never
    }
    'src/pages/introduction/frequently-asked.md': {
      routes:
        | '/introduction/frequently-asked'
      views:
        | never
    }
    'src/pages/introduction/getting-started.md': {
      routes:
        | '/introduction/getting-started'
      views:
        | never
    }
    'src/pages/releases.md': {
      routes:
        | '/releases'
      views:
        | never
    }
    'src/pages/roadmap.md': {
      routes:
        | '/roadmap'
      views:
        | never
    }
    'src/pages/storybook/index.md': {
      routes:
        | '/storybook/'
      views:
        | never
    }
    'src/pages/storybook.view.vue': {
      routes:
        | '/storybook.view'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
