/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/components': RouteRecordInfo<'/components', '/components', Record<never, never>, Record<never, never>>,
    '/composables/': RouteRecordInfo<'/composables/', '/composables', Record<never, never>, Record<never, never>>,
    '/composables/to-reactive': RouteRecordInfo<'/composables/to-reactive', '/composables/to-reactive', Record<never, never>, Record<never, never>>,
    '/composables/use-breakpoints': RouteRecordInfo<'/composables/use-breakpoints', '/composables/use-breakpoints', Record<never, never>, Record<never, never>>,
    '/composables/use-context': RouteRecordInfo<'/composables/use-context', '/composables/use-context', Record<never, never>, Record<never, never>>,
    '/composables/use-filter': RouteRecordInfo<'/composables/use-filter', '/composables/use-filter', Record<never, never>, Record<never, never>>,
    '/composables/use-group': RouteRecordInfo<'/composables/use-group', '/composables/use-group', Record<never, never>, Record<never, never>>,
    '/composables/use-hydration': RouteRecordInfo<'/composables/use-hydration', '/composables/use-hydration', Record<never, never>, Record<never, never>>,
    '/composables/use-keydown': RouteRecordInfo<'/composables/use-keydown', '/composables/use-keydown', Record<never, never>, Record<never, never>>,
    '/composables/use-locale': RouteRecordInfo<'/composables/use-locale', '/composables/use-locale', Record<never, never>, Record<never, never>>,
    '/composables/use-registrar': RouteRecordInfo<'/composables/use-registrar', '/composables/use-registrar', Record<never, never>, Record<never, never>>,
    '/composables/use-single': RouteRecordInfo<'/composables/use-single', '/composables/use-single', Record<never, never>, Record<never, never>>,
    '/composables/use-step': RouteRecordInfo<'/composables/use-step', '/composables/use-step', Record<never, never>, Record<never, never>>,
    '/composables/use-storage': RouteRecordInfo<'/composables/use-storage', '/composables/use-storage', Record<never, never>, Record<never, never>>,
    '/composables/use-theme': RouteRecordInfo<'/composables/use-theme', '/composables/use-theme', Record<never, never>, Record<never, never>>,
    '/composables/use-tokens': RouteRecordInfo<'/composables/use-tokens', '/composables/use-tokens', Record<never, never>, Record<never, never>>,
  }
}
