/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Atom: typeof import('./../../packages/v0/src/components/Atom/Atom.vue')['default']
    AvatarFallback: typeof import('./../../packages/v0/src/components/Avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./../../packages/v0/src/components/Avatar/AvatarImage.vue')['default']
    AvatarRoot: typeof import('./../../packages/v0/src/components/Avatar/AvatarRoot.vue')['default']
    GroupItem: typeof import('./../../packages/v0/src/components/Group/GroupItem.vue')['default']
    GroupRoot: typeof import('./../../packages/v0/src/components/Group/GroupRoot.vue')['default']
    StepItem: typeof import('./../../packages/v0/src/components/Step/StepItem.vue')['default']
    StepRoot: typeof import('./../../packages/v0/src/components/Step/StepRoot.vue')['default']
    V0Paper: typeof import('./../../packages/paper/src/components/V0Paper/V0Paper.vue')['default']
  }
}
