/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Atom: typeof import('./../../packages/0/src/components/Atom/Atom.vue')['default']
    AvatarFallback: typeof import('./../../packages/0/src/components/Avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./../../packages/0/src/components/Avatar/AvatarImage.vue')['default']
    AvatarRoot: typeof import('./../../packages/0/src/components/Avatar/AvatarRoot.vue')['default']
    BreakpointsItem: typeof import('./../../packages/0/src/components/Breakpoints/BreakpointsItem.vue')['default']
    BreakpointsRoot: typeof import('./../../packages/0/src/components/Breakpoints/BreakpointsRoot.vue')['default']
    ContextItem: typeof import('./../../packages/0/src/components/Context/ContextItem.vue')['default']
    ContextRoot: typeof import('./../../packages/0/src/components/Context/ContextRoot.vue')['default']
    GroupItem: typeof import('./../../packages/0/src/components/Group/GroupItem.vue')['default']
    GroupRoot: typeof import('./../../packages/0/src/components/Group/GroupRoot.vue')['default']
    Hydration: typeof import('./../../packages/0/src/components/Hydration/Hydration.vue')['default']
    HydrationRoot: typeof import('./../../packages/0/src/components/Hydration/HydrationRoot.vue')['default']
    MarkdownProvider: typeof import('./../../packages/0/src/components/Markdown/MarkdownProvider.vue')['default']
    MarkdownRoot: typeof import('./../../packages/0/src/components/Markdown/MarkdownRoot.vue')['default']
    PopoverAnchor: typeof import('./../../packages/0/src/components/Popover/PopoverAnchor.vue')['default']
    PopoverContent: typeof import('./../../packages/0/src/components/Popover/PopoverContent.vue')['default']
    PopoverRoot: typeof import('./../../packages/0/src/components/Popover/PopoverRoot.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionItem: typeof import('./../../packages/0/src/components/Selection/SelectionItem.vue')['default']
    SelectionRoot: typeof import('./../../packages/0/src/components/Selection/SelectionRoot.vue')['default']
    StepItem: typeof import('./../../packages/0/src/components/Step/StepItem.vue')['default']
    StepRoot: typeof import('./../../packages/0/src/components/Step/StepRoot.vue')['default']
    ThemeItem: typeof import('./../../packages/0/src/components/Theme/ThemeItem.vue')['default']
    ThemeRoot: typeof import('./../../packages/0/src/components/Theme/ThemeRoot.vue')['default']
    V0Paper: typeof import('./../../packages/paper/src/components/V0Paper/V0Paper.vue')['default']
  }
}
