/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const COMMON_ELEMENTS: typeof import('../../packages/0/src/constants/htmlElements').COMMON_ELEMENTS
  const ConsolaLoggerAdapter: typeof import('../../packages/0/src/composables/useLogger/index').ConsolaLoggerAdapter
  const DEFAULT_DARK: typeof import('../../packages/paper/src/composables/useTheme/index').DEFAULT_DARK
  const DEFAULT_LIGHT: typeof import('../../packages/paper/src/composables/useTheme/index').DEFAULT_LIGHT
  const EffectScope: typeof import('vue').EffectScope
  const IN_BROWSER: typeof import('../../packages/0/src/constants/globals').IN_BROWSER
  const MemoryAdapter: typeof import('../../packages/0/src/composables/useStorage/index').MemoryAdapter
  const PermissionAdapter: typeof import('../../packages/0/src/composables/usePermissions/index').PermissionAdapter
  const PinoLoggerAdapter: typeof import('../../packages/0/src/composables/useLogger/index').PinoLoggerAdapter
  const SELF_CLOSING_TAGS: typeof import('../../packages/0/src/constants/htmlElements').SELF_CLOSING_TAGS
  const SUPPORTS_INTERSECTION_OBSERVER: typeof import('../../packages/0/src/constants/globals').SUPPORTS_INTERSECTION_OBSERVER
  const SUPPORTS_MATCH_MEDIA: typeof import('../../packages/0/src/constants/globals').SUPPORTS_MATCH_MEDIA
  const SUPPORTS_MUTATION_OBSERVER: typeof import('../../packages/0/src/constants/globals').SUPPORTS_MUTATION_OBSERVER
  const SUPPORTS_OBSERVER: typeof import('../../packages/0/src/constants/globals').SUPPORTS_OBSERVER
  const SUPPORTS_TOUCH: typeof import('../../packages/0/src/constants/globals').SUPPORTS_TOUCH
  const V0_ELEVATION_KEY: typeof import('../../packages/paper/src/composables/useElevation/index').V0_ELEVATION_KEY
  const Vuetify0LocaleAdapter: typeof import('../../packages/0/src/composables/useLocale/index').Vuetify0LocaleAdapter
  const Vuetify0LoggerAdapter: typeof import('../../packages/0/src/composables/useLogger/index').Vuetify0LoggerAdapter
  const Vuetify0ThemeAdapter: typeof import('../../packages/0/src/composables/useTheme/index').Vuetify0ThemeAdapter
  const __LOGGER_ENABLED__: typeof import('../../packages/0/src/constants/globals').__LOGGER_ENABLED__
  const clamp: typeof import('../../packages/0/src/utilities/helpers').clamp
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createBreakpoints: typeof import('../../packages/0/src/composables/useBreakpoints/index').createBreakpoints
  const createBreakpointsContext: typeof import('../../packages/0/src/composables/useBreakpoints/index').createBreakpointsContext
  const createBreakpointsPlugin: typeof import('../../packages/0/src/composables/useBreakpoints/index').createBreakpointsPlugin
  const createContext: typeof import('../../packages/0/src/composables/createContext/index').createContext
  const createElevation: typeof import('../../packages/paper/src/composables/useElevation/index').createElevation
  const createFallbackHydration: typeof import('../../packages/0/src/composables/useHydration/index').createFallbackHydration
  const createFeatures: typeof import('../../packages/0/src/composables/useFeatures/index').createFeatures
  const createFeaturesContext: typeof import('../../packages/0/src/composables/useFeatures/index').createFeaturesContext
  const createFeaturesPlugin: typeof import('../../packages/0/src/composables/useFeatures/index').createFeaturesPlugin
  const createFilter: typeof import('../../packages/0/src/composables/useFilter/index').createFilter
  const createFilterContext: typeof import('../../packages/0/src/composables/useFilter/index').createFilterContext
  const createForm: typeof import('../../packages/0/src/composables/useForm/index').createForm
  const createFormContext: typeof import('../../packages/0/src/composables/useForm/index').createFormContext
  const createGroup: typeof import('../../packages/0/src/composables/createGroup/index').createGroup
  const createGroupContext: typeof import('../../packages/0/src/composables/createGroup/index').createGroupContext
  const createHydration: typeof import('../../packages/0/src/composables/useHydration/index').createHydration
  const createHydrationContext: typeof import('../../packages/0/src/composables/useHydration/index').createHydrationContext
  const createHydrationPlugin: typeof import('../../packages/0/src/composables/useHydration/index').createHydrationPlugin
  const createLocale: typeof import('../../packages/0/src/composables/useLocale/index').createLocale
  const createLocaleContext: typeof import('../../packages/0/src/composables/useLocale/index').createLocaleContext
  const createLocaleFallback: typeof import('../../packages/0/src/composables/useLocale/index').createLocaleFallback
  const createLocalePlugin: typeof import('../../packages/0/src/composables/useLocale/index').createLocalePlugin
  const createLogger: typeof import('../../packages/0/src/composables/useLogger/index').createLogger
  const createLoggerContext: typeof import('../../packages/0/src/composables/useLogger/index').createLoggerContext
  const createLoggerPlugin: typeof import('../../packages/0/src/composables/useLogger/index').createLoggerPlugin
  const createOverflow: typeof import('../../packages/0/src/composables/useOverflow/index').createOverflow
  const createOverflowContext: typeof import('../../packages/0/src/composables/useOverflow/index').createOverflowContext
  const createPagination: typeof import('../../packages/0/src/composables/usePagination/index').createPagination
  const createPaginationContext: typeof import('../../packages/0/src/composables/usePagination/index').createPaginationContext
  const createPermissions: typeof import('../../packages/0/src/composables/usePermissions/index').createPermissions
  const createPermissionsContext: typeof import('../../packages/0/src/composables/usePermissions/index').createPermissionsContext
  const createPermissionsPlugin: typeof import('../../packages/0/src/composables/usePermissions/index').createPermissionsPlugin
  const createPlugin: typeof import('../../packages/0/src/composables/createPlugin/index').createPlugin
  const createQueue: typeof import('../../packages/0/src/composables/useQueue/index').createQueue
  const createQueueContext: typeof import('../../packages/0/src/composables/useQueue/index').createQueueContext
  const createRegistry: typeof import('../../packages/0/src/composables/createRegistry/index').createRegistry
  const createRegistryContext: typeof import('../../packages/0/src/composables/createRegistry/index').createRegistryContext
  const createSelection: typeof import('../../packages/0/src/composables/createSelection/index').createSelection
  const createSelectionContext: typeof import('../../packages/0/src/composables/createSelection/index').createSelectionContext
  const createSingle: typeof import('../../packages/0/src/composables/createSingle/index').createSingle
  const createSingleContext: typeof import('../../packages/0/src/composables/createSingle/index').createSingleContext
  const createStep: typeof import('../../packages/0/src/composables/createStep/index').createStep
  const createStepContext: typeof import('../../packages/0/src/composables/createStep/index').createStepContext
  const createStorage: typeof import('../../packages/0/src/composables/useStorage/index').createStorage
  const createStorageContext: typeof import('../../packages/0/src/composables/useStorage/index').createStorageContext
  const createStoragePlugin: typeof import('../../packages/0/src/composables/useStorage/index').createStoragePlugin
  const createTheme: typeof import('../../packages/0/src/composables/useTheme/index').createTheme
  const createThemeContext: typeof import('../../packages/0/src/composables/useTheme/index').createThemeContext
  const createThemePlugin: typeof import('../../packages/0/src/composables/useTheme/index').createThemePlugin
  const createTimeline: typeof import('../../packages/0/src/composables/useTimeline/index').createTimeline
  const createTimelineContext: typeof import('../../packages/0/src/composables/useTimeline/index').createTimelineContext
  const createTokens: typeof import('../../packages/0/src/composables/useTokens/index').createTokens
  const createTokensContext: typeof import('../../packages/0/src/composables/useTokens/index').createTokensContext
  const createTrinity: typeof import('../../packages/0/src/composables/createTrinity/index').createTrinity
  const customRef: typeof import('vue').customRef
  const debounce: typeof import('../../packages/0/src/utilities/helpers').debounce
  const defaultElevationGenerator: typeof import('../../packages/paper/src/composables/useElevation/index').defaultElevationGenerator
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const genId: typeof import('../../packages/0/src/utilities/helpers').genId
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentInstanceName: typeof import('../../packages/paper/src/utilities/getCurrentInstanceName').getCurrentInstanceName
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const hexToRgba: typeof import('../../packages/paper/src/composables/useColor/index').hexToRgba
  const hexaToRgba: typeof import('../../packages/paper/src/composables/useColor/index').hexaToRgba
  const inject: typeof import('vue').inject
  const instanceExists: typeof import('../../packages/0/src/utilities/instance').instanceExists
  const instanceName: typeof import('../../packages/0/src/utilities/instance').instanceName
  const isArray: typeof import('../../packages/0/src/utilities/helpers').isArray
  const isBoolean: typeof import('../../packages/0/src/utilities/helpers').isBoolean
  const isFunction: typeof import('../../packages/0/src/utilities/helpers').isFunction
  const isNaN: typeof import('../../packages/0/src/utilities/helpers').isNaN
  const isNull: typeof import('../../packages/0/src/utilities/helpers').isNull
  const isNullOrUndefined: typeof import('../../packages/0/src/utilities/helpers').isNullOrUndefined
  const isNumber: typeof import('../../packages/0/src/utilities/helpers').isNumber
  const isObject: typeof import('../../packages/0/src/utilities/helpers').isObject
  const isPrimitive: typeof import('../../packages/0/src/utilities/helpers').isPrimitive
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isSelfClosingTag: typeof import('../../packages/0/src/constants/htmlElements').isSelfClosingTag
  const isShallow: typeof import('vue').isShallow
  const isString: typeof import('../../packages/0/src/utilities/helpers').isString
  const isSymbol: typeof import('../../packages/0/src/utilities/helpers').isSymbol
  const isUndefined: typeof import('../../packages/0/src/utilities/helpers').isUndefined
  const markRaw: typeof import('vue').markRaw
  const mergeDeep: typeof import('../../packages/0/src/utilities/helpers').mergeDeep
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parseColor: typeof import('../../packages/paper/src/composables/useColor/index').parseColor
  const provide: typeof import('vue').provide
  const provideContext: typeof import('../../packages/0/src/composables/createContext/index').provideContext
  const range: typeof import('../../packages/0/src/utilities/helpers').range
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const rgbToRgba: typeof import('../../packages/paper/src/composables/useColor/index').rgbToRgba
  const rgbaToHexa: typeof import('../../packages/paper/src/composables/useColor/index').rgbaToHexa
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toArray: typeof import('../../packages/0/src/composables/toArray/index').toArray
  const toCamelCase: typeof import('../../packages/paper/src/utilities/helpers').toCamelCase
  const toKebabCase: typeof import('../../packages/paper/src/utilities/helpers').toKebabCase
  const toRaw: typeof import('vue').toRaw
  const toReactive: typeof import('../../packages/0/src/composables/toReactive/index').toReactive
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useBorder: typeof import('../../packages/paper/src/composables/useBorder/index').useBorder
  const useBreakpoints: typeof import('../../packages/0/src/composables/useBreakpoints/index').useBreakpoints
  const useClickOutside: typeof import('../../packages/0/src/composables/useClickOutside/index').useClickOutside
  const useColor: typeof import('../../packages/paper/src/composables/useColor/index').useColor
  const useContext: typeof import('../../packages/0/src/composables/createContext/index').useContext
  const useContrast: typeof import('../../packages/paper/src/composables/useContrast/index').useContrast
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDimensions: typeof import('../../packages/paper/src/composables/useDimensions/index').useDimensions
  const useDocumentEventListener: typeof import('../../packages/0/src/composables/useEventListener/index').useDocumentEventListener
  const useElementIntersection: typeof import('../../packages/0/src/composables/useIntersectionObserver/index').useElementIntersection
  const useElementSize: typeof import('../../packages/0/src/composables/useResizeObserver/index').useElementSize
  const useElevation: typeof import('../../packages/paper/src/composables/useElevation/index').useElevation
  const useEventListener: typeof import('../../packages/0/src/composables/useEventListener/index').useEventListener
  const useFeatures: typeof import('../../packages/0/src/composables/useFeatures/index').useFeatures
  const useFilter: typeof import('../../packages/0/src/composables/useFilter/index').useFilter
  const useFilterContext: typeof import('../../packages/0/src/composables/useFilter/index').useFilterContext
  const useForm: typeof import('../../packages/0/src/composables/useForm/index').useForm
  const useGroup: typeof import('../../packages/0/src/composables/createGroup/index').useGroup
  const useHotkey: typeof import('../../packages/0/src/composables/useHotkey/index').useHotkey
  const useHydration: typeof import('../../packages/0/src/composables/useHydration/index').useHydration
  const useId: typeof import('vue').useId
  const useIntersectionObserver: typeof import('../../packages/0/src/composables/useIntersectionObserver/index').useIntersectionObserver
  const useLocale: typeof import('../../packages/0/src/composables/useLocale/index').useLocale
  const useLogger: typeof import('../../packages/0/src/composables/useLogger/index').useLogger
  const useMediaQuery: typeof import('../../packages/0/src/composables/useMediaQuery/index').useMediaQuery
  const useModel: typeof import('vue').useModel
  const useMutationObserver: typeof import('../../packages/0/src/composables/useMutationObserver/index').useMutationObserver
  const useOverflow: typeof import('../../packages/0/src/composables/useOverflow/index').useOverflow
  const usePagination: typeof import('../../packages/0/src/composables/usePagination/index').usePagination
  const usePermissions: typeof import('../../packages/0/src/composables/usePermissions/index').usePermissions
  const usePrefersContrast: typeof import('../../packages/0/src/composables/useMediaQuery/index').usePrefersContrast
  const usePrefersDark: typeof import('../../packages/0/src/composables/useMediaQuery/index').usePrefersDark
  const usePrefersReducedMotion: typeof import('../../packages/0/src/composables/useMediaQuery/index').usePrefersReducedMotion
  const useProxyModel: typeof import('../../packages/0/src/composables/useProxyModel/index').useProxyModel
  const useProxyRegistry: typeof import('../../packages/0/src/composables/useProxyRegistry/index').useProxyRegistry
  const useQueue: typeof import('../../packages/0/src/composables/useQueue/index').useQueue
  const useRegistry: typeof import('../../packages/0/src/composables/useRegistry/index').useRegistry
  const useResizeObserver: typeof import('../../packages/0/src/composables/useResizeObserver/index').useResizeObserver
  const useRounded: typeof import('../../packages/paper/src/composables/useRounded/index').useRounded
  const useSelection: typeof import('../../packages/0/src/composables/createSelection/index').useSelection
  const useSingle: typeof import('../../packages/0/src/composables/createSingle/index').useSingle
  const useSlots: typeof import('vue').useSlots
  const useSpacing: typeof import('../../packages/paper/src/composables/useSpacing/index').useSpacing
  const useStep: typeof import('../../packages/0/src/composables/createStep/index').useStep
  const useStorage: typeof import('../../packages/0/src/composables/useStorage/index').useStorage
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTheme: typeof import('../../packages/0/src/composables/useTheme/index').useTheme
  const useTimeline: typeof import('../../packages/0/src/composables/useTimeline/index').useTimeline
  const useToggleScope: typeof import('../../packages/0/src/composables/useToggleScope/index').useToggleScope
  const useTokens: typeof import('../../packages/0/src/composables/useTokens/index').useTokens
  const useVirtual: typeof import('../../packages/0/src/composables/useVirtual/index').useVirtual
  const useWindowEventListener: typeof import('../../packages/0/src/composables/useEventListener/index').useWindowEventListener
  const version: typeof import('../../packages/0/src/constants/globals').version
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { BorderProps } from '../../packages/paper/src/composables/useBorder/index'
  import('../../packages/paper/src/composables/useBorder/index')
  // @ts-ignore
  export type { ColorProps } from '../../packages/paper/src/composables/useColor/index'
  import('../../packages/paper/src/composables/useColor/index')
  // @ts-ignore
  export type { DimensionProps } from '../../packages/paper/src/composables/useDimensions/index'
  import('../../packages/paper/src/composables/useDimensions/index')
  // @ts-ignore
  export type { ElevationConfig, ElevationOptions, ElevationProps } from '../../packages/paper/src/composables/useElevation/index'
  import('../../packages/paper/src/composables/useElevation/index')
  // @ts-ignore
  export type { RoundedProps } from '../../packages/paper/src/composables/useRounded/index'
  import('../../packages/paper/src/composables/useRounded/index')
  // @ts-ignore
  export type { SpacingProps } from '../../packages/paper/src/composables/useSpacing/index'
  import('../../packages/paper/src/composables/useSpacing/index')
  // @ts-ignore
  export type { Theme, ThemeProvider } from '../../packages/paper/src/composables/useTheme/index'
  import('../../packages/paper/src/composables/useTheme/index')
  // @ts-ignore
  export type { ContextKey, CreateContextOptions } from '../../packages/0/src/composables/createContext/index'
  import('../../packages/0/src/composables/createContext/index')
  // @ts-ignore
  export type { PluginOptions, Plugin } from '../../packages/0/src/composables/createPlugin/index'
  import('../../packages/0/src/composables/createPlugin/index')
  // @ts-ignore
  export type { ContextTrinity } from '../../packages/0/src/composables/createTrinity/index'
  import('../../packages/0/src/composables/createTrinity/index')
  // @ts-ignore
  export type { BreakpointName, BreakpointsContext, BreakpointsOptions, BreakpointsPluginOptions, BreakpointsContextOptions } from '../../packages/0/src/composables/useBreakpoints/index'
  import('../../packages/0/src/composables/useBreakpoints/index')
  // @ts-ignore
  export type { ClickOutsideElement, ClickOutsideTarget, ClickOutsideIgnoreTarget, UseClickOutsideOptions, UseClickOutsideReturn } from '../../packages/0/src/composables/useClickOutside/index'
  import('../../packages/0/src/composables/useClickOutside/index')
  // @ts-ignore
  export type { CleanupFunction, EventHandler } from '../../packages/0/src/composables/useEventListener/index'
  import('../../packages/0/src/composables/useEventListener/index')
  // @ts-ignore
  export type { FeatureTicket, FeatureContext, FeatureOptions, FeatureContextOptions, FeaturePluginOptions } from '../../packages/0/src/composables/useFeatures/index'
  import('../../packages/0/src/composables/useFeatures/index')
  // @ts-ignore
  export type { Primitive, FilterQuery, FilterItem, FilterMode, FilterFunction, FilterOptions, FilterResult, FilterContext, FilterContextOptions } from '../../packages/0/src/composables/useFilter/index'
  import('../../packages/0/src/composables/useFilter/index')
  // @ts-ignore
  export type { FormValidationResult, FormValidationRule, FormValue, FormTicket, FormContext, FormOptions, FormContextOptions } from '../../packages/0/src/composables/useForm/index'
  import('../../packages/0/src/composables/useForm/index')
  // @ts-ignore
  export type { GroupTicket, GroupContext, GroupOptions, GroupContextOptions } from '../../packages/0/src/composables/createGroup/index'
  import('../../packages/0/src/composables/createGroup/index')
  // @ts-ignore
  export type { UseHotkeyOptions, UseHotkeyReturn, PlatformContext } from '../../packages/0/src/composables/useHotkey/index'
  import('../../packages/0/src/composables/useHotkey/index')
  // @ts-ignore
  export type { HydrationContext, HydrationOptions, HydrationContextOptions, HydrationPluginOptions } from '../../packages/0/src/composables/useHydration/index'
  import('../../packages/0/src/composables/useHydration/index')
  // @ts-ignore
  export type { MaybeRef, IntersectionObserverEntry, IntersectionObserverOptions, UseIntersectionObserverReturn, UseElementIntersectionReturn } from '../../packages/0/src/composables/useIntersectionObserver/index'
  import('../../packages/0/src/composables/useIntersectionObserver/index')
  // @ts-ignore
  export type { LocaleRecord, LocaleTicket, LocaleContext, LocaleOptions, LocaleContextOptions, LocalePluginOptions, LocaleAdapter } from '../../packages/0/src/composables/useLocale/index'
  import('../../packages/0/src/composables/useLocale/index')
  // @ts-ignore
  export type { LoggerContext, LoggerOptions, LoggerContextOptions, LoggerPluginOptions, LoggerAdapter, LogLevel } from '../../packages/0/src/composables/useLogger/index'
  import('../../packages/0/src/composables/useLogger/index')
  // @ts-ignore
  export type { MediaQueryContext } from '../../packages/0/src/composables/useMediaQuery/index'
  import('../../packages/0/src/composables/useMediaQuery/index')
  // @ts-ignore
  export type { MutationObserverRecord, UseMutationObserverOptions, UseMutationObserverReturn } from '../../packages/0/src/composables/useMutationObserver/index'
  import('../../packages/0/src/composables/useMutationObserver/index')
  // @ts-ignore
  export type { OverflowOptions, OverflowContext, OverflowContextOptions } from '../../packages/0/src/composables/useOverflow/index'
  import('../../packages/0/src/composables/useOverflow/index')
  // @ts-ignore
  export type { PaginationTicket, PaginationContext, PaginationOptions, PaginationContextOptions } from '../../packages/0/src/composables/usePagination/index'
  import('../../packages/0/src/composables/usePagination/index')
  // @ts-ignore
  export type { PermissionTicket, PermissionContext, PermissionOptions, PermissionContextOptions, PermissionPluginOptions, PermissionAdapterInterface } from '../../packages/0/src/composables/usePermissions/index'
  import('../../packages/0/src/composables/usePermissions/index')
  // @ts-ignore
  export type { ProxyModelOptions } from '../../packages/0/src/composables/useProxyModel/index'
  import('../../packages/0/src/composables/useProxyModel/index')
  // @ts-ignore
  export type { ProxyRegistryOptions, ProxyRegistryContext } from '../../packages/0/src/composables/useProxyRegistry/index'
  import('../../packages/0/src/composables/useProxyRegistry/index')
  // @ts-ignore
  export type { QueueTicket, QueueContext, QueueOptions, QueueContextOptions } from '../../packages/0/src/composables/useQueue/index'
  import('../../packages/0/src/composables/useQueue/index')
  // @ts-ignore
  export type { RegistryTicket, RegistryEventCallback, RegistryContext, RegistryOptions, RegistryContextOptions } from '../../packages/0/src/composables/createRegistry/index'
  import('../../packages/0/src/composables/createRegistry/index')
  // @ts-ignore
  export type { ResizeObserverEntry, ResizeObserverOptions, UseResizeObserverReturn, UseElementSizeReturn } from '../../packages/0/src/composables/useResizeObserver/index'
  import('../../packages/0/src/composables/useResizeObserver/index')
  // @ts-ignore
  export type { SelectionTicket, SelectionContext, SelectionOptions, SelectionContextOptions } from '../../packages/0/src/composables/createSelection/index'
  import('../../packages/0/src/composables/createSelection/index')
  // @ts-ignore
  export type { SingleTicket, SingleContext, SingleOptions, SingleContextOptions } from '../../packages/0/src/composables/createSingle/index'
  import('../../packages/0/src/composables/createSingle/index')
  // @ts-ignore
  export type { StepTicket, StepContext, StepOptions, StepContextOptions } from '../../packages/0/src/composables/createStep/index'
  import('../../packages/0/src/composables/createStep/index')
  // @ts-ignore
  export type { StorageContext, StorageOptions, StorageContextOptions, StoragePluginOptions, StorageAdapter, StorageType } from '../../packages/0/src/composables/useStorage/index'
  import('../../packages/0/src/composables/useStorage/index')
  // @ts-ignore
  export type { Colors, ThemeColors, ThemeRecord, ThemeTicket, ThemeContext, ThemeOptions, ThemeContextOptions, ThemePluginOptions, ThemeAdapter } from '../../packages/0/src/composables/useTheme/index'
  import('../../packages/0/src/composables/useTheme/index')
  // @ts-ignore
  export type { TimelineContext, TimelineTicket, TimelineOptions, TimelineContextOptions } from '../../packages/0/src/composables/useTimeline/index'
  import('../../packages/0/src/composables/useTimeline/index')
  // @ts-ignore
  export type { ToggleScopeControls } from '../../packages/0/src/composables/useToggleScope/index'
  import('../../packages/0/src/composables/useToggleScope/index')
  // @ts-ignore
  export type { TokenAlias, TokenPrimitive, TokenValue, TokenCollection, FlatTokenCollection, TokenTicket, TokenContext, TokenOptions, TokenContextOptions } from '../../packages/0/src/composables/useTokens/index'
  import('../../packages/0/src/composables/useTokens/index')
  // @ts-ignore
  export type { VirtualDirection, VirtualState, VirtualAnchor, ScrollToOptions, VirtualOptions, VirtualItem, VirtualContext } from '../../packages/0/src/composables/useVirtual/index'
  import('../../packages/0/src/composables/useVirtual/index')
  // @ts-ignore
  export type { HTMLElementName, SelfClosingElement } from '../../packages/0/src/constants/htmlElements'
  import('../../packages/0/src/constants/htmlElements')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly COMMON_ELEMENTS: UnwrapRef<typeof import('../../packages/0/src/constants/htmlElements')['COMMON_ELEMENTS']>
    readonly ConsolaLoggerAdapter: UnwrapRef<typeof import('../../packages/0/src/composables/useLogger/index')['ConsolaLoggerAdapter']>
    readonly DEFAULT_DARK: UnwrapRef<typeof import('../../packages/paper/src/composables/useTheme/index')['DEFAULT_DARK']>
    readonly DEFAULT_LIGHT: UnwrapRef<typeof import('../../packages/paper/src/composables/useTheme/index')['DEFAULT_LIGHT']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly IN_BROWSER: UnwrapRef<typeof import('../../packages/0/src/constants/globals')['IN_BROWSER']>
    readonly MemoryAdapter: UnwrapRef<typeof import('../../packages/0/src/composables/useStorage/index')['MemoryAdapter']>
    readonly PermissionAdapter: UnwrapRef<typeof import('../../packages/0/src/composables/usePermissions/index')['PermissionAdapter']>
    readonly PinoLoggerAdapter: UnwrapRef<typeof import('../../packages/0/src/composables/useLogger/index')['PinoLoggerAdapter']>
    readonly SELF_CLOSING_TAGS: UnwrapRef<typeof import('../../packages/0/src/constants/htmlElements')['SELF_CLOSING_TAGS']>
    readonly SUPPORTS_INTERSECTION_OBSERVER: UnwrapRef<typeof import('../../packages/0/src/constants/globals')['SUPPORTS_INTERSECTION_OBSERVER']>
    readonly SUPPORTS_MATCH_MEDIA: UnwrapRef<typeof import('../../packages/0/src/constants/globals')['SUPPORTS_MATCH_MEDIA']>
    readonly SUPPORTS_MUTATION_OBSERVER: UnwrapRef<typeof import('../../packages/0/src/constants/globals')['SUPPORTS_MUTATION_OBSERVER']>
    readonly SUPPORTS_OBSERVER: UnwrapRef<typeof import('../../packages/0/src/constants/globals')['SUPPORTS_OBSERVER']>
    readonly SUPPORTS_TOUCH: UnwrapRef<typeof import('../../packages/0/src/constants/globals')['SUPPORTS_TOUCH']>
    readonly V0_ELEVATION_KEY: UnwrapRef<typeof import('../../packages/paper/src/composables/useElevation/index')['V0_ELEVATION_KEY']>
    readonly Vuetify0LocaleAdapter: UnwrapRef<typeof import('../../packages/0/src/composables/useLocale/index')['Vuetify0LocaleAdapter']>
    readonly Vuetify0LoggerAdapter: UnwrapRef<typeof import('../../packages/0/src/composables/useLogger/index')['Vuetify0LoggerAdapter']>
    readonly Vuetify0ThemeAdapter: UnwrapRef<typeof import('../../packages/0/src/composables/useTheme/index')['Vuetify0ThemeAdapter']>
    readonly __LOGGER_ENABLED__: UnwrapRef<typeof import('../../packages/0/src/constants/globals')['__LOGGER_ENABLED__']>
    readonly clamp: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['clamp']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createBreakpoints: UnwrapRef<typeof import('../../packages/0/src/composables/useBreakpoints/index')['createBreakpoints']>
    readonly createBreakpointsContext: UnwrapRef<typeof import('../../packages/0/src/composables/useBreakpoints/index')['createBreakpointsContext']>
    readonly createBreakpointsPlugin: UnwrapRef<typeof import('../../packages/0/src/composables/useBreakpoints/index')['createBreakpointsPlugin']>
    readonly createContext: UnwrapRef<typeof import('../../packages/0/src/composables/createContext/index')['createContext']>
    readonly createElevation: UnwrapRef<typeof import('../../packages/paper/src/composables/useElevation/index')['createElevation']>
    readonly createFallbackHydration: UnwrapRef<typeof import('../../packages/0/src/composables/useHydration/index')['createFallbackHydration']>
    readonly createFeatures: UnwrapRef<typeof import('../../packages/0/src/composables/useFeatures/index')['createFeatures']>
    readonly createFeaturesContext: UnwrapRef<typeof import('../../packages/0/src/composables/useFeatures/index')['createFeaturesContext']>
    readonly createFeaturesPlugin: UnwrapRef<typeof import('../../packages/0/src/composables/useFeatures/index')['createFeaturesPlugin']>
    readonly createFilter: UnwrapRef<typeof import('../../packages/0/src/composables/useFilter/index')['createFilter']>
    readonly createFilterContext: UnwrapRef<typeof import('../../packages/0/src/composables/useFilter/index')['createFilterContext']>
    readonly createForm: UnwrapRef<typeof import('../../packages/0/src/composables/useForm/index')['createForm']>
    readonly createFormContext: UnwrapRef<typeof import('../../packages/0/src/composables/useForm/index')['createFormContext']>
    readonly createGroup: UnwrapRef<typeof import('../../packages/0/src/composables/createGroup/index')['createGroup']>
    readonly createGroupContext: UnwrapRef<typeof import('../../packages/0/src/composables/createGroup/index')['createGroupContext']>
    readonly createHydration: UnwrapRef<typeof import('../../packages/0/src/composables/useHydration/index')['createHydration']>
    readonly createHydrationContext: UnwrapRef<typeof import('../../packages/0/src/composables/useHydration/index')['createHydrationContext']>
    readonly createHydrationPlugin: UnwrapRef<typeof import('../../packages/0/src/composables/useHydration/index')['createHydrationPlugin']>
    readonly createLocale: UnwrapRef<typeof import('../../packages/0/src/composables/useLocale/index')['createLocale']>
    readonly createLocaleContext: UnwrapRef<typeof import('../../packages/0/src/composables/useLocale/index')['createLocaleContext']>
    readonly createLocaleFallback: UnwrapRef<typeof import('../../packages/0/src/composables/useLocale/index')['createLocaleFallback']>
    readonly createLocalePlugin: UnwrapRef<typeof import('../../packages/0/src/composables/useLocale/index')['createLocalePlugin']>
    readonly createLogger: UnwrapRef<typeof import('../../packages/0/src/composables/useLogger/index')['createLogger']>
    readonly createLoggerContext: UnwrapRef<typeof import('../../packages/0/src/composables/useLogger/index')['createLoggerContext']>
    readonly createLoggerPlugin: UnwrapRef<typeof import('../../packages/0/src/composables/useLogger/index')['createLoggerPlugin']>
    readonly createOverflow: UnwrapRef<typeof import('../../packages/0/src/composables/useOverflow/index')['createOverflow']>
    readonly createOverflowContext: UnwrapRef<typeof import('../../packages/0/src/composables/useOverflow/index')['createOverflowContext']>
    readonly createPagination: UnwrapRef<typeof import('../../packages/0/src/composables/usePagination/index')['createPagination']>
    readonly createPaginationContext: UnwrapRef<typeof import('../../packages/0/src/composables/usePagination/index')['createPaginationContext']>
    readonly createPermissions: UnwrapRef<typeof import('../../packages/0/src/composables/usePermissions/index')['createPermissions']>
    readonly createPermissionsContext: UnwrapRef<typeof import('../../packages/0/src/composables/usePermissions/index')['createPermissionsContext']>
    readonly createPermissionsPlugin: UnwrapRef<typeof import('../../packages/0/src/composables/usePermissions/index')['createPermissionsPlugin']>
    readonly createPlugin: UnwrapRef<typeof import('../../packages/0/src/composables/createPlugin/index')['createPlugin']>
    readonly createQueue: UnwrapRef<typeof import('../../packages/0/src/composables/useQueue/index')['createQueue']>
    readonly createQueueContext: UnwrapRef<typeof import('../../packages/0/src/composables/useQueue/index')['createQueueContext']>
    readonly createRegistry: UnwrapRef<typeof import('../../packages/0/src/composables/createRegistry/index')['createRegistry']>
    readonly createRegistryContext: UnwrapRef<typeof import('../../packages/0/src/composables/createRegistry/index')['createRegistryContext']>
    readonly createSelection: UnwrapRef<typeof import('../../packages/0/src/composables/createSelection/index')['createSelection']>
    readonly createSelectionContext: UnwrapRef<typeof import('../../packages/0/src/composables/createSelection/index')['createSelectionContext']>
    readonly createSingle: UnwrapRef<typeof import('../../packages/0/src/composables/createSingle/index')['createSingle']>
    readonly createSingleContext: UnwrapRef<typeof import('../../packages/0/src/composables/createSingle/index')['createSingleContext']>
    readonly createStep: UnwrapRef<typeof import('../../packages/0/src/composables/createStep/index')['createStep']>
    readonly createStepContext: UnwrapRef<typeof import('../../packages/0/src/composables/createStep/index')['createStepContext']>
    readonly createStorage: UnwrapRef<typeof import('../../packages/0/src/composables/useStorage/index')['createStorage']>
    readonly createStorageContext: UnwrapRef<typeof import('../../packages/0/src/composables/useStorage/index')['createStorageContext']>
    readonly createStoragePlugin: UnwrapRef<typeof import('../../packages/0/src/composables/useStorage/index')['createStoragePlugin']>
    readonly createTheme: UnwrapRef<typeof import('../../packages/0/src/composables/useTheme/index')['createTheme']>
    readonly createThemeContext: UnwrapRef<typeof import('../../packages/0/src/composables/useTheme/index')['createThemeContext']>
    readonly createThemePlugin: UnwrapRef<typeof import('../../packages/0/src/composables/useTheme/index')['createThemePlugin']>
    readonly createTimeline: UnwrapRef<typeof import('../../packages/0/src/composables/useTimeline/index')['createTimeline']>
    readonly createTimelineContext: UnwrapRef<typeof import('../../packages/0/src/composables/useTimeline/index')['createTimelineContext']>
    readonly createTokens: UnwrapRef<typeof import('../../packages/0/src/composables/useTokens/index')['createTokens']>
    readonly createTokensContext: UnwrapRef<typeof import('../../packages/0/src/composables/useTokens/index')['createTokensContext']>
    readonly createTrinity: UnwrapRef<typeof import('../../packages/0/src/composables/createTrinity/index')['createTrinity']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly debounce: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['debounce']>
    readonly defaultElevationGenerator: UnwrapRef<typeof import('../../packages/paper/src/composables/useElevation/index')['defaultElevationGenerator']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly genId: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['genId']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentInstanceName: UnwrapRef<typeof import('../../packages/paper/src/utilities/getCurrentInstanceName')['getCurrentInstanceName']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hexToRgba: UnwrapRef<typeof import('../../packages/paper/src/composables/useColor/index')['hexToRgba']>
    readonly hexaToRgba: UnwrapRef<typeof import('../../packages/paper/src/composables/useColor/index')['hexaToRgba']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly instanceExists: UnwrapRef<typeof import('../../packages/0/src/utilities/instance')['instanceExists']>
    readonly instanceName: UnwrapRef<typeof import('../../packages/0/src/utilities/instance')['instanceName']>
    readonly isArray: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isArray']>
    readonly isBoolean: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isBoolean']>
    readonly isFunction: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isFunction']>
    readonly isNaN: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isNaN']>
    readonly isNull: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isNull']>
    readonly isNullOrUndefined: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isNullOrUndefined']>
    readonly isNumber: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isNumber']>
    readonly isObject: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isObject']>
    readonly isPrimitive: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isPrimitive']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isSelfClosingTag: UnwrapRef<typeof import('../../packages/0/src/constants/htmlElements')['isSelfClosingTag']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isString: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isString']>
    readonly isSymbol: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isSymbol']>
    readonly isUndefined: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['isUndefined']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly mergeDeep: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['mergeDeep']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly parseColor: UnwrapRef<typeof import('../../packages/paper/src/composables/useColor/index')['parseColor']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly provideContext: UnwrapRef<typeof import('../../packages/0/src/composables/createContext/index')['provideContext']>
    readonly range: UnwrapRef<typeof import('../../packages/0/src/utilities/helpers')['range']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly rgbToRgba: UnwrapRef<typeof import('../../packages/paper/src/composables/useColor/index')['rgbToRgba']>
    readonly rgbaToHexa: UnwrapRef<typeof import('../../packages/paper/src/composables/useColor/index')['rgbaToHexa']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly toArray: UnwrapRef<typeof import('../../packages/0/src/composables/toArray/index')['toArray']>
    readonly toCamelCase: UnwrapRef<typeof import('../../packages/paper/src/utilities/helpers')['toCamelCase']>
    readonly toKebabCase: UnwrapRef<typeof import('../../packages/paper/src/utilities/helpers')['toKebabCase']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toReactive: UnwrapRef<typeof import('../../packages/0/src/composables/toReactive/index')['toReactive']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useBorder: UnwrapRef<typeof import('../../packages/paper/src/composables/useBorder/index')['useBorder']>
    readonly useBreakpoints: UnwrapRef<typeof import('../../packages/0/src/composables/useBreakpoints/index')['useBreakpoints']>
    readonly useClickOutside: UnwrapRef<typeof import('../../packages/0/src/composables/useClickOutside/index')['useClickOutside']>
    readonly useColor: UnwrapRef<typeof import('../../packages/paper/src/composables/useColor/index')['useColor']>
    readonly useContext: UnwrapRef<typeof import('../../packages/0/src/composables/createContext/index')['useContext']>
    readonly useContrast: UnwrapRef<typeof import('../../packages/paper/src/composables/useContrast/index')['useContrast']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDimensions: UnwrapRef<typeof import('../../packages/paper/src/composables/useDimensions/index')['useDimensions']>
    readonly useDocumentEventListener: UnwrapRef<typeof import('../../packages/0/src/composables/useEventListener/index')['useDocumentEventListener']>
    readonly useElementIntersection: UnwrapRef<typeof import('../../packages/0/src/composables/useIntersectionObserver/index')['useElementIntersection']>
    readonly useElementSize: UnwrapRef<typeof import('../../packages/0/src/composables/useResizeObserver/index')['useElementSize']>
    readonly useElevation: UnwrapRef<typeof import('../../packages/paper/src/composables/useElevation/index')['useElevation']>
    readonly useEventListener: UnwrapRef<typeof import('../../packages/0/src/composables/useEventListener/index')['useEventListener']>
    readonly useFeatures: UnwrapRef<typeof import('../../packages/0/src/composables/useFeatures/index')['useFeatures']>
    readonly useFilter: UnwrapRef<typeof import('../../packages/0/src/composables/useFilter/index')['useFilter']>
    readonly useFilterContext: UnwrapRef<typeof import('../../packages/0/src/composables/useFilter/index')['useFilterContext']>
    readonly useForm: UnwrapRef<typeof import('../../packages/0/src/composables/useForm/index')['useForm']>
    readonly useGroup: UnwrapRef<typeof import('../../packages/0/src/composables/createGroup/index')['useGroup']>
    readonly useHotkey: UnwrapRef<typeof import('../../packages/0/src/composables/useHotkey/index')['useHotkey']>
    readonly useHydration: UnwrapRef<typeof import('../../packages/0/src/composables/useHydration/index')['useHydration']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useIntersectionObserver: UnwrapRef<typeof import('../../packages/0/src/composables/useIntersectionObserver/index')['useIntersectionObserver']>
    readonly useLocale: UnwrapRef<typeof import('../../packages/0/src/composables/useLocale/index')['useLocale']>
    readonly useLogger: UnwrapRef<typeof import('../../packages/0/src/composables/useLogger/index')['useLogger']>
    readonly useMediaQuery: UnwrapRef<typeof import('../../packages/0/src/composables/useMediaQuery/index')['useMediaQuery']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useMutationObserver: UnwrapRef<typeof import('../../packages/0/src/composables/useMutationObserver/index')['useMutationObserver']>
    readonly useOverflow: UnwrapRef<typeof import('../../packages/0/src/composables/useOverflow/index')['useOverflow']>
    readonly usePagination: UnwrapRef<typeof import('../../packages/0/src/composables/usePagination/index')['usePagination']>
    readonly usePermissions: UnwrapRef<typeof import('../../packages/0/src/composables/usePermissions/index')['usePermissions']>
    readonly usePrefersContrast: UnwrapRef<typeof import('../../packages/0/src/composables/useMediaQuery/index')['usePrefersContrast']>
    readonly usePrefersDark: UnwrapRef<typeof import('../../packages/0/src/composables/useMediaQuery/index')['usePrefersDark']>
    readonly usePrefersReducedMotion: UnwrapRef<typeof import('../../packages/0/src/composables/useMediaQuery/index')['usePrefersReducedMotion']>
    readonly useProxyModel: UnwrapRef<typeof import('../../packages/0/src/composables/useProxyModel/index')['useProxyModel']>
    readonly useProxyRegistry: UnwrapRef<typeof import('../../packages/0/src/composables/useProxyRegistry/index')['useProxyRegistry']>
    readonly useQueue: UnwrapRef<typeof import('../../packages/0/src/composables/useQueue/index')['useQueue']>
    readonly useResizeObserver: UnwrapRef<typeof import('../../packages/0/src/composables/useResizeObserver/index')['useResizeObserver']>
    readonly useRounded: UnwrapRef<typeof import('../../packages/paper/src/composables/useRounded/index')['useRounded']>
    readonly useSelection: UnwrapRef<typeof import('../../packages/0/src/composables/createSelection/index')['useSelection']>
    readonly useSingle: UnwrapRef<typeof import('../../packages/0/src/composables/createSingle/index')['useSingle']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSpacing: UnwrapRef<typeof import('../../packages/paper/src/composables/useSpacing/index')['useSpacing']>
    readonly useStep: UnwrapRef<typeof import('../../packages/0/src/composables/createStep/index')['useStep']>
    readonly useStorage: UnwrapRef<typeof import('../../packages/0/src/composables/useStorage/index')['useStorage']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTheme: UnwrapRef<typeof import('../../packages/0/src/composables/useTheme/index')['useTheme']>
    readonly useTimeline: UnwrapRef<typeof import('../../packages/0/src/composables/useTimeline/index')['useTimeline']>
    readonly useToggleScope: UnwrapRef<typeof import('../../packages/0/src/composables/useToggleScope/index')['useToggleScope']>
    readonly useTokens: UnwrapRef<typeof import('../../packages/0/src/composables/useTokens/index')['useTokens']>
    readonly useVirtual: UnwrapRef<typeof import('../../packages/0/src/composables/useVirtual/index')['useVirtual']>
    readonly useWindowEventListener: UnwrapRef<typeof import('../../packages/0/src/composables/useEventListener/index')['useWindowEventListener']>
    readonly version: UnwrapRef<typeof import('../../packages/0/src/constants/globals')['version']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}