/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Atom: typeof import('./../../packages/0/src/components/Atom/Atom.vue')['default']
    AvatarFallback: typeof import('./../../packages/0/src/components/Avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./../../packages/0/src/components/Avatar/AvatarImage.vue')['default']
    AvatarRoot: typeof import('./../../packages/0/src/components/Avatar/AvatarRoot.vue')['default']
    BreadcrumbsRoot: typeof import('./../../packages/0/src/components/Breadcrumbs/BreadcrumbsRoot.vue')['default']
    CheckboxGroup: typeof import('./../../packages/0/src/components/Checkbox/CheckboxGroup.vue')['default']
    CheckboxHiddenInput: typeof import('./../../packages/0/src/components/Checkbox/CheckboxHiddenInput.vue')['default']
    CheckboxIndicator: typeof import('./../../packages/0/src/components/Checkbox/CheckboxIndicator.vue')['default']
    CheckboxRoot: typeof import('./../../packages/0/src/components/Checkbox/CheckboxRoot.vue')['default']
    CheckboxSelectAll: typeof import('./../../packages/0/src/components/Checkbox/CheckboxSelectAll.vue')['default']
    DialogActivator: typeof import('./../../packages/0/src/components/Dialog/DialogActivator.vue')['default']
    DialogClose: typeof import('./../../packages/0/src/components/Dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./../../packages/0/src/components/Dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./../../packages/0/src/components/Dialog/DialogDescription.vue')['default']
    DialogRoot: typeof import('./../../packages/0/src/components/Dialog/DialogRoot.vue')['default']
    DialogTitle: typeof import('./../../packages/0/src/components/Dialog/DialogTitle.vue')['default']
    ExpansionPanelActivator: typeof import('./../../packages/0/src/components/ExpansionPanel/ExpansionPanelActivator.vue')['default']
    ExpansionPanelContent: typeof import('./../../packages/0/src/components/ExpansionPanel/ExpansionPanelContent.vue')['default']
    ExpansionPanelHeader: typeof import('./../../packages/0/src/components/ExpansionPanel/ExpansionPanelHeader.vue')['default']
    ExpansionPanelItem: typeof import('./../../packages/0/src/components/ExpansionPanel/ExpansionPanelItem.vue')['default']
    ExpansionPanelRoot: typeof import('./../../packages/0/src/components/ExpansionPanel/ExpansionPanelRoot.vue')['default']
    GroupItem: typeof import('./../../packages/0/src/components/Group/GroupItem.vue')['default']
    GroupRoot: typeof import('./../../packages/0/src/components/Group/GroupRoot.vue')['default']
    PaginationEllipsis: typeof import('./../../packages/0/src/components/Pagination/PaginationEllipsis.vue')['default']
    PaginationFirst: typeof import('./../../packages/0/src/components/Pagination/PaginationFirst.vue')['default']
    PaginationItem: typeof import('./../../packages/0/src/components/Pagination/PaginationItem.vue')['default']
    PaginationLast: typeof import('./../../packages/0/src/components/Pagination/PaginationLast.vue')['default']
    PaginationNext: typeof import('./../../packages/0/src/components/Pagination/PaginationNext.vue')['default']
    PaginationPrev: typeof import('./../../packages/0/src/components/Pagination/PaginationPrev.vue')['default']
    PaginationRoot: typeof import('./../../packages/0/src/components/Pagination/PaginationRoot.vue')['default']
    PaginationStatus: typeof import('./../../packages/0/src/components/Pagination/PaginationStatus.vue')['default']
    PopoverActivator: typeof import('./../../packages/0/src/components/Popover/PopoverActivator.vue')['default']
    PopoverContent: typeof import('./../../packages/0/src/components/Popover/PopoverContent.vue')['default']
    PopoverRoot: typeof import('./../../packages/0/src/components/Popover/PopoverRoot.vue')['default']
    RadioGroup: typeof import('./../../packages/0/src/components/Radio/RadioGroup.vue')['default']
    RadioHiddenInput: typeof import('./../../packages/0/src/components/Radio/RadioHiddenInput.vue')['default']
    RadioIndicator: typeof import('./../../packages/0/src/components/Radio/RadioIndicator.vue')['default']
    RadioRoot: typeof import('./../../packages/0/src/components/Radio/RadioRoot.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrim: typeof import('./../../packages/0/src/components/Scrim/Scrim.vue')['default']
    SelectionItem: typeof import('./../../packages/0/src/components/Selection/SelectionItem.vue')['default']
    SelectionRoot: typeof import('./../../packages/0/src/components/Selection/SelectionRoot.vue')['default']
    SingleItem: typeof import('./../../packages/0/src/components/Single/SingleItem.vue')['default']
    SingleRoot: typeof import('./../../packages/0/src/components/Single/SingleRoot.vue')['default']
    StepItem: typeof import('./../../packages/0/src/components/Step/StepItem.vue')['default']
    StepRoot: typeof import('./../../packages/0/src/components/Step/StepRoot.vue')['default']
    TabsItem: typeof import('./../../packages/0/src/components/Tabs/TabsItem.vue')['default']
    TabsList: typeof import('./../../packages/0/src/components/Tabs/TabsList.vue')['default']
    TabsPanel: typeof import('./../../packages/0/src/components/Tabs/TabsPanel.vue')['default']
    TabsRoot: typeof import('./../../packages/0/src/components/Tabs/TabsRoot.vue')['default']
    TabsTab: typeof import('./../../packages/0/src/components/Tabs/TabsTab.vue')['default']
    V0Paper: typeof import('./../../packages/paper/src/components/V0Paper/V0Paper.vue')['default']
  }
}
