/**
 * Prebake dist/theme.css for zero-config install:
 *   import '@paper/emerald/theme.css'
 *
 * Self-contained (no @vuetify/v0 import) so it runs after tsdown without
 * requiring packages/0 dist to be built first.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { emeraldColors } from '../src/colors'
import {
  fontFamily,
  fontSize,
  icon,
  radius,
  shadow,
  spacing,
  stroke,
} from '../src/theme'

const SAFE_IDENT = /^[a-zA-Z0-9_-]+$/
const UNSAFE_CSS = /url\s*\(|@import|expression\s*\(|[{}]/i

const V0_ALIAS_KEYS = [
  'primary',
  'on-primary',
  'secondary',
  'on-secondary',
  'background',
  'on-background',
  'surface',
  'on-surface',
  'surface-tint',
  'divider',
  'border',
  'pre',
  'danger',
  'on-danger',
  'alert',
  'on-alert',
  'success',
  'on-success',
  'info',
  'on-info',
] as const

function hexToChannels (hex: string): string | null {
  if (!/^#[0-9a-f]{3,8}$/i.test(hex)) return null
  let h = hex.slice(1)
  h = h.length === 3 || h.length === 4 ? h.split('').map(c => c + c).join('').slice(0, 6) : h.slice(0, 6)
  const n = Number.parseInt(h, 16)
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`
}

function foundations (): string {
  const lines: string[] = []

  for (const [key, val] of Object.entries(spacing)) {
    lines.push(`  --emerald-spacing-${key}: ${val};`)
  }
  for (const [key, val] of Object.entries(radius)) {
    lines.push(`  --emerald-radius-${key}: ${val};`)
  }
  for (const [key, val] of Object.entries(stroke)) {
    lines.push(`  --emerald-stroke-${key}: ${val};`)
  }
  for (const [key, val] of Object.entries(icon)) {
    lines.push(`  --emerald-icon-${key}: ${val};`)
  }
  for (const [key, val] of Object.entries(shadow)) {
    lines.push(`  --emerald-shadow-${key}: ${val};`)
  }
  lines.push(`  --emerald-font-sans: ${fontFamily.sans};`)
  for (const [key, val] of Object.entries(fontSize)) {
    const [size, meta] = val
    lines.push(
      `  --emerald-text-${key}-size: ${size};`,
      `  --emerald-text-${key}-height: ${meta.lineHeight};`,
      `  --emerald-text-${key}-weight: ${meta.fontWeight};`,
    )
  }

  return `:root {\n${lines.join('\n')}\n}\n`
}

function colorBlock (selector: string): string {
  const lines: string[] = []

  for (const [key, val] of Object.entries(emeraldColors)) {
    if (!SAFE_IDENT.test(key) || UNSAFE_CSS.test(val)) continue
    lines.push(`  --emerald-${key}: ${val};`)
    const channels = hexToChannels(val)
    if (channels) lines.push(`  --emerald-${key}-channels: ${channels};`)
  }

  for (const key of V0_ALIAS_KEYS) {
    if (key in emeraldColors) {
      lines.push(`  --v0-${key}: var(--emerald-${key});`)
    }
  }
  if ('success' in emeraldColors) lines.push('  --v0-success: var(--emerald-success);')
  if ('info' in emeraldColors) lines.push('  --v0-info: var(--emerald-info);')
  if ('alert' in emeraldColors) lines.push('  --v0-warning: var(--emerald-alert);')
  if ('danger' in emeraldColors) lines.push('  --v0-error: var(--emerald-danger);')
  if ('primary' in emeraldColors) lines.push('  --v0-accent: var(--emerald-primary);')

  lines.push('  color: var(--emerald-on-background);')

  return `${selector} {\n${lines.join('\n')}\n}\n`
}

const here = dirname(fileURLToPath(import.meta.url))
const out = resolve(here, '../dist/theme.css')
const banner = '/* @paper/emerald — prebaked default theme. Generated by scripts/bake-theme.ts. Do not edit. */\n'
const css = banner
  + foundations()
  + colorBlock('[data-theme="emerald"]')
  + colorBlock(':root')
  + ':root {\n  color-scheme: light;\n}\n'

mkdirSync(dirname(out), { recursive: true })
writeFileSync(out, css)
console.log(`[bake-theme] wrote ${out} (${css.length} bytes)`)
