/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./components/app/AppShell.vue')['default']
    BuildSwitcher: typeof import('./components/app/BuildSwitcher.vue')['default']
    ComponentInfo: typeof import('./components/ComponentInfo.vue')['default']
    Icon: typeof import('./components/app/Icon.vue')['default']
    MiniFrame: typeof import('./components/preview/MiniFrame.vue')['default']
    PluginConfigShell: typeof import('./components/PluginConfigShell.vue')['default']
    PreviewBreakpoints: typeof import('./components/preview/PreviewBreakpoints.vue')['default']
    PreviewDate: typeof import('./components/preview/PreviewDate.vue')['default']
    PreviewFeatures: typeof import('./components/preview/PreviewFeatures.vue')['default']
    PreviewLocale: typeof import('./components/preview/PreviewLocale.vue')['default']
    PreviewLogger: typeof import('./components/preview/PreviewLogger.vue')['default']
    PreviewNotifications: typeof import('./components/preview/PreviewNotifications.vue')['default']
    PreviewPane: typeof import('./components/preview/PreviewPane.vue')['default']
    PreviewPermissions: typeof import('./components/preview/PreviewPermissions.vue')['default']
    PreviewReducedMotion: typeof import('./components/preview/PreviewReducedMotion.vue')['default']
    PreviewRtl: typeof import('./components/preview/PreviewRtl.vue')['default']
    PreviewRules: typeof import('./components/preview/PreviewRules.vue')['default']
    PreviewStack: typeof import('./components/preview/PreviewStack.vue')['default']
    PreviewStorage: typeof import('./components/preview/PreviewStorage.vue')['default']
    PreviewSummary: typeof import('./components/preview/PreviewSummary.vue')['default']
    PreviewTheme: typeof import('./components/preview/PreviewTheme.vue')['default']
    PreviewTooltip: typeof import('./components/preview/PreviewTooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepBar: typeof import('./components/app/StepBar.vue')['default']
    ThemeToggle: typeof import('./components/app/ThemeToggle.vue')['default']
  }
}
