// Types
export interface ThemeDefinition {
  id: string
  label: string
  icon: string
  dark: boolean
  colors: Record<string, string>
}

export type ThemeId = keyof typeof themes

/**
 * All available themes for the docs site.
 * Colors follow the v0 theme token format.
 */
export const themes = {
  'light': {
    id: 'light',
    label: 'Light',
    icon: 'theme-light',
    dark: false,
    colors: {
      'primary': '#7c5cf6',
      'secondary': '#64748b',
      'accent': '#6366f1',
      'error': '#ef4444',
      'info': '#1867c0',
      'success': '#22c55e',
      'warning': '#f59e0b',
      'background': '#ffffff',
      'surface': '#ffffff',
      'surface-tint': '#f5f5f5',
      'surface-variant': '#e8e8e8',
      'divider': '#e0e0e0',
      'pre': '{light.colors.surface-tint}',
      'on-primary': '#ffffff',
      'on-secondary': '#ffffff',
      'on-accent': '#1a1a1a',
      'on-error': '#ffffff',
      'on-info': '#ffffff',
      'on-success': '#1a1a1a',
      'on-warning': '#1a1a1a',
      'on-background': '#212121',
      'on-surface': '#212121',
      'on-surface-variant': '#666666',
      'glass-surface': 'rgba(255, 255, 255, 0.85)',
      'scrollbar-thumb': '#b0b0b0',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'dark': {
    id: 'dark',
    label: 'Dark',
    icon: 'theme-dark',
    dark: true,
    colors: {
      'primary': '#c4b5fd',
      'secondary': '#94a3b8',
      'accent': '#c084fc',
      'error': '#f87171',
      'info': '#38bdf8',
      'success': '#4ade80',
      'warning': '#fb923c',
      'background': '#121212',
      'surface': '#1a1a1a',
      'surface-tint': '#2a2a2a',
      'surface-variant': '#1e1e1e',
      'divider': '#404040',
      'pre': '{dark.colors.surface-tint}',
      'on-primary': '#1a1a1a',
      'on-secondary': '#ffffff',
      'on-accent': '#ffffff',
      'on-error': '#1a1a1a',
      'on-info': '#1a1a1a',
      'on-success': '#1a1a1a',
      'on-warning': '#1a1a1a',
      'on-background': '#e0e0e0',
      'on-surface': '#e0e0e0',
      'on-surface-variant': '#a0a0a0',
      'glass-surface': 'rgba(26, 26, 26, 0.7)',
      'scrollbar-thumb': '#505050',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'high-contrast': {
    id: 'high-contrast',
    label: 'High Contrast',
    icon: 'theme-high-contrast',
    dark: true,
    colors: {
      'primary': '#ffff00',
      'secondary': '#00ffff',
      'accent': '#ff00ff',
      'error': '#ff0000',
      'info': '#00ffff',
      'success': '#00ff00',
      'warning': '#ffff00',
      'background': '#000000',
      'surface': '#000000',
      'surface-tint': '#1a1a1a',
      'surface-variant': '#000000',
      'divider': '#ffffff',
      'pre': '#0a0a0a',
      'on-primary': '#000000',
      'on-secondary': '#000000',
      'on-accent': '#000000',
      'on-error': '#000000',
      'on-info': '#000000',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#ffffff',
      'on-surface': '#ffffff',
      'on-surface-variant': '#ffffff',
      'glass-surface': 'rgba(0, 0, 0, 0.85)',
      'scrollbar-thumb': '#ffffff',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'protanopia': {
    id: 'protanopia',
    label: 'Protanopia',
    icon: 'theme-protanopia',
    dark: true,
    colors: {
      'primary': '#56b4e9',
      'secondary': '#e69f00',
      'accent': '#f0e442',
      'error': '#d55e00',
      'info': '#56b4e9',
      'success': '#009e73',
      'warning': '#e69f00',
      'background': '#1a1a2e',
      'surface': '#16213e',
      'surface-tint': '#1f2b4a',
      'surface-variant': '#1a2540',
      'divider': '#3a4a6a',
      'pre': '#141c30',
      'on-primary': '#000000',
      'on-secondary': '#000000',
      'on-accent': '#000000',
      'on-error': '#ffffff',
      'on-info': '#000000',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#e8e8e8',
      'on-surface': '#e8e8e8',
      'on-surface-variant': '#a0a8b8',
      'glass-surface': 'rgba(22, 33, 62, 0.8)',
      'scrollbar-thumb': 'rgba(86, 180, 233, 0.4)',
    },
  },
  'deuteranopia': {
    id: 'deuteranopia',
    label: 'Deuteranopia',
    icon: 'theme-deuteranopia',
    dark: true,
    colors: {
      'primary': '#648fff',
      'secondary': '#ffb000',
      'accent': '#dc267f',
      'error': '#fe6100',
      'info': '#648fff',
      'success': '#785ef0',
      'warning': '#ffb000',
      'background': '#1b1b2f',
      'surface': '#1f1f3a',
      'surface-tint': '#282848',
      'surface-variant': '#232340',
      'divider': '#3d3d5c',
      'pre': '#181830',
      'on-primary': '#000000',
      'on-secondary': '#000000',
      'on-accent': '#ffffff',
      'on-error': '#000000',
      'on-info': '#000000',
      'on-success': '#ffffff',
      'on-warning': '#000000',
      'on-background': '#e8e8f0',
      'on-surface': '#e8e8f0',
      'on-surface-variant': '#a0a0b8',
      'glass-surface': 'rgba(31, 31, 58, 0.8)',
      'scrollbar-thumb': 'rgba(100, 143, 255, 0.4)',
    },
  },
  'tritanopia': {
    id: 'tritanopia',
    label: 'Tritanopia',
    icon: 'theme-tritanopia',
    dark: true,
    colors: {
      'primary': '#ff6b6b',
      'secondary': '#4ecdc4',
      'accent': '#ffe66d',
      'error': '#ff4757',
      'info': '#45b7d1',
      'success': '#26de81',
      'warning': '#fed330',
      'background': '#1a1a1a',
      'surface': '#2d2d2d',
      'surface-tint': '#383838',
      'surface-variant': '#333333',
      'divider': '#4a4a4a',
      'pre': '#242424',
      'on-primary': '#000000',
      'on-secondary': '#000000',
      'on-accent': '#000000',
      'on-error': '#000000',
      'on-info': '#000000',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#f0f0f0',
      'on-surface': '#f0f0f0',
      'on-surface-variant': '#b0b0b0',
      'glass-surface': 'rgba(45, 45, 45, 0.8)',
      'scrollbar-thumb': 'rgba(255, 107, 107, 0.4)',
    },
  },
  'blackguard': {
    id: 'blackguard',
    label: 'Blackguard',
    icon: 'theme-blackguard',
    dark: true,
    colors: {
      'primary': '#f59e0b',
      'secondary': '#a78bfa',
      'accent': '#f472b6',
      'error': '#f87171',
      'info': '#c084fc',
      'success': '#86efac',
      'warning': '#fbbf24',
      'background': '#0f0c24',
      'surface': '#1a1640',
      'surface-tint': '#252050',
      'surface-variant': '#1e1845',
      'divider': 'rgba(167, 139, 250, 0.2)',
      'pre': '#151230',
      'on-primary': '#000000',
      'on-secondary': '#000000',
      'on-accent': '#000000',
      'on-error': '#000000',
      'on-info': '#000000',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#e8e0f0',
      'on-surface': '#e8e0f0',
      'on-surface-variant': '#a0a0b0',
      'glass-surface': 'rgba(26, 22, 64, 0.7)',
      'scrollbar-thumb': 'rgba(167, 139, 250, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'polaris': {
    id: 'polaris',
    label: 'Polaris',
    icon: 'theme-polaris',
    dark: true,
    colors: {
      'primary': '#f97316',
      'secondary': '#14b8a6',
      'accent': '#8b5cf6',
      'error': '#ef4444',
      'info': '#0ea5e9',
      'success': '#22c55e',
      'warning': '#eab308',
      'background': '#0c0a09',
      'surface': '#1c1917',
      'surface-tint': '#292524',
      'surface-variant': '#292524',
      'divider': '#3d3835',
      'pre': '#1c1917',
      'on-primary': '#000000',
      'on-secondary': '#000000',
      'on-accent': '#ffffff',
      'on-error': '#000000',
      'on-info': '#000000',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#fafaf9',
      'on-surface': '#fafaf9',
      'on-surface-variant': '#a8a29e',
      'glass-surface': 'rgba(28, 25, 23, 0.7)',
      'scrollbar-thumb': 'rgba(249, 115, 22, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'nebula': {
    id: 'nebula',
    label: 'Nebula',
    icon: 'theme-nebula',
    dark: true,
    colors: {
      'primary': '#60a5fa',
      'secondary': '#38bdf8',
      'accent': '#22d3ee',
      'error': '#f87171',
      'info': '#94a3b8',
      'success': '#34d399',
      'warning': '#fbbf24',
      'background': '#0f172a',
      'surface': '#1e293b',
      'surface-tint': '#273548',
      'surface-variant': '#1e293b',
      'divider': 'rgba(96, 165, 250, 0.2)',
      'pre': '#0f172a',
      'on-primary': '#000000',
      'on-secondary': '#000000',
      'on-accent': '#000000',
      'on-error': '#000000',
      'on-info': '#000000',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#e2e8f0',
      'on-surface': '#e2e8f0',
      'on-surface-variant': '#94a3b8',
      'glass-surface': 'rgba(30, 41, 59, 0.7)',
      'scrollbar-thumb': 'rgba(96, 165, 250, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'odyssey': {
    id: 'odyssey',
    label: 'Odyssey',
    icon: 'theme-odyssey',
    dark: false,
    colors: {
      'primary': '#3E805B',
      'secondary': '#0d9488',
      'accent': '#d4af37',
      'error': '#e11d48',
      'info': '#0d9488',
      'success': '#10b981',
      'warning': '#d97706',
      'background': '#FAF9F6',
      'surface': '#ffffff',
      'surface-tint': '#F0EDE8',
      'surface-variant': '#E8E5DF',
      'divider': '#D4D1C7',
      'pre': '#F0EDE8',
      'on-primary': '#ffffff',
      'on-secondary': '#ffffff',
      'on-accent': '#000000',
      'on-error': '#ffffff',
      'on-info': '#ffffff',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#1C1B1A',
      'on-surface': '#1C1B1A',
      'on-surface-variant': '#57534e',
      'glass-surface': 'rgba(250, 249, 246, 0.85)',
      'scrollbar-thumb': '#a8a29e',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'tailwind': {
    id: 'tailwind',
    label: 'Tailwind',
    icon: 'theme-tailwind',
    dark: true,
    colors: {
      'primary': '#38bdf8',
      'secondary': '#818cf8',
      'accent': '#f472b6',
      'error': '#f87171',
      'info': '#38bdf8',
      'success': '#4ade80',
      'warning': '#fbbf24',
      'background': '#0f172a',
      'surface': '#1e293b',
      'surface-tint': '#334155',
      'surface-variant': '#1e293b',
      'divider': '#475569',
      'pre': '{tailwind.colors.surface-tint}',
      'on-primary': '#000000',
      'on-secondary': '#ffffff',
      'on-accent': '#000000',
      'on-error': '#000000',
      'on-info': '#000000',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#e2e8f0',
      'on-surface': '#e2e8f0',
      'on-surface-variant': '#94a3b8',
      'glass-surface': 'rgba(30, 41, 59, 0.7)',
      'scrollbar-thumb': 'rgba(56, 189, 248, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'tailwind-light': {
    id: 'tailwind-light',
    label: 'Tailwind',
    icon: 'theme-tailwind',
    dark: false,
    colors: {
      'primary': '#0ea5e9',
      'secondary': '#6366f1',
      'accent': '#ec4899',
      'error': '#ef4444',
      'info': '#0ea5e9',
      'success': '#22c55e',
      'warning': '#f59e0b',
      'background': '#ffffff',
      'surface': '#ffffff',
      'surface-tint': '#f8fafc',
      'surface-variant': '#f1f5f9',
      'divider': '#e2e8f0',
      'pre': '{tailwind-light.colors.surface-tint}',
      'on-primary': '#ffffff',
      'on-secondary': '#ffffff',
      'on-accent': '#ffffff',
      'on-error': '#ffffff',
      'on-info': '#ffffff',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#0f172a',
      'on-surface': '#0f172a',
      'on-surface-variant': '#64748b',
      'glass-surface': 'rgba(255, 255, 255, 0.85)',
      'scrollbar-thumb': 'rgba(14, 165, 233, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'material-3': {
    id: 'material-3',
    label: 'Material 3',
    icon: 'theme-material-3',
    dark: true,
    colors: {
      'primary': '#D0BCFF',
      'secondary': '#CCC2DC',
      'accent': '#EFB8C8',
      'error': '#F2B8B5',
      'info': '#D0BCFF',
      'success': '#7DC67E',
      'warning': '#E8C064',
      'background': '#1c1b1f',
      'surface': '#2b2930',
      'surface-tint': '#36343b',
      'surface-variant': '#49454f',
      'divider': '#49454f',
      'pre': '{material-3.colors.surface-tint}',
      'on-primary': '#000000',
      'on-secondary': '#000000',
      'on-accent': '#000000',
      'on-error': '#000000',
      'on-info': '#000000',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#e6e1e5',
      'on-surface': '#e6e1e5',
      'on-surface-variant': '#cac4d0',
      'glass-surface': 'rgba(43, 41, 48, 0.7)',
      'scrollbar-thumb': 'rgba(208, 188, 255, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'material-3-light': {
    id: 'material-3-light',
    label: 'Material 3',
    icon: 'theme-material-3',
    dark: false,
    colors: {
      'primary': '#6750A4',
      'secondary': '#625B71',
      'accent': '#7D5260',
      'error': '#B3261E',
      'info': '#6750A4',
      'success': '#386A20',
      'warning': '#7D5700',
      'background': '#FFFBFE',
      'surface': '#FFFBFE',
      'surface-tint': '#F7F2FA',
      'surface-variant': '#E7E0EC',
      'divider': '#CAC4D0',
      'pre': '{material-3-light.colors.surface-tint}',
      'on-primary': '#ffffff',
      'on-secondary': '#ffffff',
      'on-accent': '#ffffff',
      'on-error': '#ffffff',
      'on-info': '#ffffff',
      'on-success': '#ffffff',
      'on-warning': '#ffffff',
      'on-background': '#1C1B1F',
      'on-surface': '#1C1B1F',
      'on-surface-variant': '#49454F',
      'glass-surface': 'rgba(255, 251, 254, 0.85)',
      'scrollbar-thumb': 'rgba(103, 80, 164, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'ant-design': {
    id: 'ant-design',
    label: 'Ant Design',
    icon: 'theme-ant-design',
    dark: true,
    colors: {
      'primary': '#1677ff',
      'secondary': '#722ed1',
      'accent': '#13c2c2',
      'error': '#ff4d4f',
      'info': '#1677ff',
      'success': '#52c41a',
      'warning': '#faad14',
      'background': '#141414',
      'surface': '#1f1f1f',
      'surface-tint': '#303030',
      'surface-variant': '#1f1f1f',
      'divider': '#424242',
      'pre': '{ant-design.colors.surface-tint}',
      'on-primary': '#ffffff',
      'on-secondary': '#ffffff',
      'on-accent': '#000000',
      'on-error': '#ffffff',
      'on-info': '#ffffff',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#e8e8e8',
      'on-surface': '#e8e8e8',
      'on-surface-variant': '#8c8c8c',
      'glass-surface': 'rgba(31, 31, 31, 0.7)',
      'scrollbar-thumb': 'rgba(22, 119, 255, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'ant-design-light': {
    id: 'ant-design-light',
    label: 'Ant Design',
    icon: 'theme-ant-design',
    dark: false,
    colors: {
      'primary': '#1677ff',
      'secondary': '#722ed1',
      'accent': '#13c2c2',
      'error': '#ff4d4f',
      'info': '#1677ff',
      'success': '#52c41a',
      'warning': '#faad14',
      'background': '#ffffff',
      'surface': '#ffffff',
      'surface-tint': '#fafafa',
      'surface-variant': '#f5f5f5',
      'divider': '#d9d9d9',
      'pre': '{ant-design-light.colors.surface-tint}',
      'on-primary': '#ffffff',
      'on-secondary': '#ffffff',
      'on-accent': '#000000',
      'on-error': '#ffffff',
      'on-info': '#ffffff',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#141414',
      'on-surface': '#141414',
      'on-surface-variant': '#8c8c8c',
      'glass-surface': 'rgba(255, 255, 255, 0.85)',
      'scrollbar-thumb': 'rgba(22, 119, 255, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'radix': {
    id: 'radix',
    label: 'Radix',
    icon: 'theme-radix',
    dark: true,
    colors: {
      'primary': '#5b5bd6',
      'secondary': '#7c66dc',
      'accent': '#ab4aba',
      'error': '#e5484d',
      'info': '#3e63dd',
      'success': '#29a383',
      'warning': '#f5d90a',
      'background': '#111113',
      'surface': '#18191b',
      'surface-tint': '#212225',
      'surface-variant': '#18191b',
      'divider': '#2b2c2f',
      'pre': '{radix.colors.surface-tint}',
      'on-primary': '#ffffff',
      'on-secondary': '#ffffff',
      'on-accent': '#ffffff',
      'on-error': '#ffffff',
      'on-info': '#ffffff',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#eeeef0',
      'on-surface': '#eeeef0',
      'on-surface-variant': '#6f6f78',
      'glass-surface': 'rgba(24, 25, 27, 0.7)',
      'scrollbar-thumb': 'rgba(91, 91, 214, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
  'radix-light': {
    id: 'radix-light',
    label: 'Radix',
    icon: 'theme-radix',
    dark: false,
    colors: {
      'primary': '#5b5bd6',
      'secondary': '#7c66dc',
      'accent': '#ab4aba',
      'error': '#e5484d',
      'info': '#3e63dd',
      'success': '#29a383',
      'warning': '#f5d90a',
      'background': '#ffffff',
      'surface': '#fcfcfd',
      'surface-tint': '#f9f9fb',
      'surface-variant': '#f0f0f3',
      'divider': '#dcdce6',
      'pre': '{radix-light.colors.surface-tint}',
      'on-primary': '#ffffff',
      'on-secondary': '#ffffff',
      'on-accent': '#ffffff',
      'on-error': '#ffffff',
      'on-info': '#ffffff',
      'on-success': '#000000',
      'on-warning': '#000000',
      'on-background': '#111113',
      'on-surface': '#111113',
      'on-surface-variant': '#6f6f78',
      'glass-surface': 'rgba(255, 255, 255, 0.85)',
      'scrollbar-thumb': 'rgba(91, 91, 214, 0.4)',
      'discord': '{palette.brand.discord}',
      'vue': '{palette.brand.vue}',
      'mastered': '{palette.brand.mastered}',
      'github': '#24292f',
    },
  },
} as const satisfies Record<string, ThemeDefinition>

/**
 * Get all theme configs for createThemePlugin.
 */
export function getAllThemeConfigs (): Record<ThemeId, { dark: boolean, colors: Record<string, string> }> {
  const result = {} as Record<ThemeId, { dark: boolean, colors: Record<string, string> }>
  for (const id of Object.keys(themes) as ThemeId[]) {
    const theme = themes[id]
    result[id] = { dark: theme.dark, colors: { ...theme.colors } }
  }
  return result
}

/**
 * Export theme as Vuetify config format.
 * Ready to paste into createVuetify() themes option.
 */
export function exportThemeAsVuetifyConfig (id: ThemeId): string {
  const theme = themes[id]
  const config = {
    dark: theme.dark,
    colors: { ...theme.colors },
  }

  // Format as JS object (not JSON) for better DX
  const colorsStr = Object.entries(config.colors)
    .map(([key, value]) => `      '${key}': '${value}',`)
    .join('\n')

  return `{
  dark: ${config.dark},
  colors: {
${colorsStr}
  },
}`
}
