/**
 * @fileoverview Self-hosted coverage badge.
 *
 * Computes overall statement coverage for the published package from a v8
 * `coverage-final.json` and writes a shields.io *endpoint* badge JSON. The
 * README points a `https://img.shields.io/endpoint?url=…` shield at the raw
 * file on master, so the coverage badge no longer depends on Codecov
 * processing our uploads (which silently stopped producing commit reports).
 *
 * Regenerated by the metrics pipeline (see generate-metrics.js), committed
 * through the metrics-regen auto-PR alongside benchmarks.json / metrics.json.
 */
import { writeFileSync } from 'node:fs'

// Only the shipped library counts toward the badge — mirror the coverage
// scope CI uploads use (packages/0/src), and skip test/bench sources.
function isSource (filePath) {
  return filePath.includes('packages/0/src')
    && !filePath.includes('.test.')
    && !filePath.includes('.bench.')
}

/**
 * Overall statement coverage across the published source, as a percentage
 * rounded to one decimal. Returns null when no source files are present so
 * callers can refuse to emit a misleading badge.
 */
export function computeCoverageTotal (coverage) {
  let covered = 0
  let total = 0

  for (const [filePath, data] of Object.entries(coverage)) {
    if (!isSource(filePath) || !data?.s) continue
    const statements = Object.values(data.s)
    total += statements.length
    covered += statements.filter(hits => hits > 0).length
  }

  if (total === 0) return null

  return Math.round((covered / total) * 1000) / 10
}

// shields.io named colors, matched to the thresholds Codecov used.
function colorFor (pct) {
  if (pct >= 95) return 'brightgreen'
  if (pct >= 90) return 'green'
  if (pct >= 80) return 'yellowgreen'
  if (pct >= 70) return 'yellow'
  if (pct >= 60) return 'orange'
  return 'red'
}

/**
 * Write the shields endpoint badge for `coverage` to `outPath`. Returns the
 * computed percentage, or null when there was nothing to measure (no file
 * written in that case — a stale badge beats a "0%" one).
 */
export function writeCoverageBadge (coverage, outPath) {
  const pct = computeCoverageTotal(coverage)
  if (pct === null) return null

  const badge = {
    schemaVersion: 1,
    label: 'coverage',
    message: `${Math.round(pct)}%`,
    color: colorFor(pct),
  }

  writeFileSync(outPath, `${JSON.stringify(badge, null, 2)}\n`)
  return pct
}
