/**
 * Generates the inventory sections of skills/vuetify0/SKILL.md from the
 * package's own metadata so the skill can never silently drift from the
 * real API surface.
 *
 * Ground truth:
 * - packages/0/src/composables/index.ts — barrel re-exports (public composables)
 * - packages/0/src/components/index.ts — barrel re-exports (public components)
 * - packages/0/src/utilities/index.ts — module re-exports, parsed per export
 * - packages/0/src/maturity.json — level, category, notes
 *
 * Any mismatch between the barrels and maturity.json is a hard error in both
 * directions. The single exception: `draft` maturity entries may be absent
 * from the barrels, because draft means planned but not yet exported.
 *
 * Run manually:  pnpm skill
 * Drift check:   pnpm skill --check (no writes, exit 1 on any difference)
 */

import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

interface Entry {
  level: 'stable' | 'preview' | 'draft'
  since?: string
  category: string
  notes?: string
}

type Section = Record<string, Entry>

interface Maturity {
  composables: Section
  components: Section
  utilities: Section
}

interface Mismatch {
  kind: string
  missing: string[]
  stale: string[]
}

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = resolve(ROOT, 'packages/0/src')
const SKILL = resolve(ROOT, 'skills/vuetify0/SKILL.md')
const NOTICE = '<!-- Generated by scripts/generate-skill.ts — do not edit by hand. -->'
const DECLARATION = /^export (?:async )?(?:function|class|const|let) ([$\w]+)/gm

function capitalize (value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

function mark (level: Entry['level']): string {
  return level === 'preview' ? '' : ` (${level})`
}

interface Reexport {
  name: string
  path?: string
}

/**
 * Public names re-exported by a barrel, with the module path retained for
 * plain star re-exports. Handles `export * from`, `export * as ns from`,
 * and `export { a, b as c } from`, single- or double-quoted. Type-only
 * re-exports (`export type … from` and inline `type` specifiers) are
 * deliberately excluded: maturity.json tracks runtime features, and types
 * ride along with their owning module. Any other `export … from './…'`
 * line is a hard error so new forms force a decision here instead of
 * silently vanishing from the inventory.
 */
async function barrel (file: string): Promise<Reexport[]> {
  const content = await readFile(file, 'utf8')
  const found: Reexport[] = []
  for (const raw of content.split('\n')) {
    const line = raw.trim().replace(/;$/, '')
    if (!/^export\b.*\bfrom ['"]\.\//.test(line)) continue
    if (/^export type\b/.test(line)) continue
    const star = line.match(/^export \* from ['"]\.\/([^'"]+)['"]$/)
    if (star) {
      found.push({ name: star[1], path: star[1] })
      continue
    }
    const namespace = line.match(/^export \* as ([$\w]+) from ['"]\.\/[^'"]+['"]$/)
    if (namespace) {
      found.push({ name: namespace[1] })
      continue
    }
    const named = line.match(/^export \{([^}]+)\} from ['"]\.\/[^'"]+['"]$/)
    if (named) {
      for (const specifier of named[1].split(',')) {
        const binding = specifier.trim()
        if (!binding || binding.startsWith('type ')) continue
        const parts = binding.split(/\s+as\s+/)
        found.push({ name: (parts.at(-1) ?? binding).trim() })
      }
      continue
    }
    throw new Error(`${file}: unrecognized re-export line: ${line}`)
  }
  return found
}

/** True when the comment block directly above a declaration carries `@internal`. */
function internal (content: string, index: number): boolean {
  const lines = content.slice(0, index).split('\n')
  lines.pop()
  for (let line = lines.length - 1; line >= 0; line--) {
    const text = lines[line].trim()
    const comment = text.startsWith('//') || text.startsWith('/*') || text.startsWith('*')
    if (!comment) return false
    if (text.includes('@internal')) return true
  }
  return false
}

/**
 * Runtime exports of the utility modules, mapped to their module source for
 * gloss extraction. Type-only exports never match, `@internal` ones are skipped.
 */
async function utilities (): Promise<Map<string, string>> {
  const found = new Map<string, string>()
  for (const { name, path } of await barrel(resolve(SRC, 'utilities/index.ts'))) {
    if (!path) {
      throw new Error(`utilities/index.ts: "${name}" is not a star re-export — its module cannot be parsed for the public surface`)
    }
    const content = await readFile(resolve(SRC, `utilities/${path}.ts`), 'utf8')
    for (const match of content.matchAll(DECLARATION)) {
      if (internal(content, match.index)) continue
      found.set(match[1], content)
    }
  }
  return found
}

/** Leading prose of a JSDoc paragraph, cut before any bullet list. */
function lead (paragraph: string): string {
  const lines: string[] = []
  for (const line of paragraph.split('\n')) {
    if (/^\s*[-*]\s/.test(line)) break
    lines.push(line)
  }
  return lines.join(' ')
}

/** First sentence of a JSDoc paragraph, whitespace collapsed. */
function sentence (text: string): string | undefined {
  const flat = lead(text).replace(/\s+/g, ' ').trim()
  if (!flat || flat.startsWith('@')) return undefined
  const match = flat.match(/^.*?\.(?=\s|$)/)
  let result = (match ? match[0] : flat).trim()
  if (result.endsWith(':')) result = result.slice(0, -1).replace(/ with$/, '').trim()
  return result || undefined
}

/** First sentence of the `@remarks` block in a module-level JSDoc header. */
function remarks (content: string): string | undefined {
  const match = content.match(/^\/\*\*([^]*?)\*\//)
  if (!match || !match[1].includes('@module')) return undefined
  const body = match[1].replace(/^\s*\* ?/gm, '')
  const tail = body.split('@remarks')[1]
  if (!tail) return undefined
  return sentence(tail.split(/\n\s*\n/)[0])
}

/** Whether text contains only whitespace and comments. Linear scan — an equivalent regex is ambiguous and superlinear on slash runs. */
function trivia (text: string): boolean {
  let index = 0
  while (index < text.length) {
    if (/\s/.test(text[index])) {
      index++
    } else if (text.startsWith('/*', index)) {
      const end = text.indexOf('*/', index + 2)
      if (end === -1) return false
      index = end + 2
    } else if (text.startsWith('//', index)) {
      const end = text.indexOf('\n', index)
      index = end === -1 ? text.length : end + 1
    } else {
      return false
    }
  }
  return true
}

/** First sentence of the JSDoc block directly above the named export. */
function jsdoc (content: string, name: string): string | undefined {
  const declaration = new RegExp(String.raw`^export (?:async )?(?:function|class|const|let) ${name}\b`, 'm')
  const match = declaration.exec(content)
  if (!match) return undefined
  const head = content.slice(0, match.index)
  const open = head.lastIndexOf('/**')
  if (open === -1) return undefined
  const close = head.indexOf('*/', open)
  if (close === -1) return undefined
  if (!trivia(head.slice(close + 2))) return undefined
  const body = head.slice(open + 3, close).replace(/^\s*\* ?/gm, '')
  const paragraph = body.split(/\n\s*\n/).map(part => part.trim()).find(part => part && !part.startsWith('@'))
  if (!paragraph) return undefined
  return sentence(paragraph)
}

/** Gloss priority: maturity notes → module/export JSDoc → none. Never fabricates. */
async function composableGloss (name: string, entry: Entry): Promise<string | undefined> {
  if (entry.notes) return entry.notes
  const content = await readFile(resolve(SRC, `composables/${name}/index.ts`), 'utf8').catch(() => '')
  if (!content) return undefined
  return remarks(content) ?? jsdoc(content, name)
}

function utilityGloss (name: string, entry: Entry, modules: Map<string, string>): string | undefined {
  if (entry.notes) return entry.notes
  const content = modules.get(name)
  if (!content) return undefined
  return jsdoc(content, name)
}

/**
 * Bidirectional drift guard between an export surface and a maturity.json
 * section. `draft` entries are exempt from the export check only.
 */
function validate (kind: string, exported: Iterable<string>, tracked: Section): Mismatch {
  const names = new Set(exported)
  const missing: string[] = []
  const stale: string[] = []
  for (const name of names) {
    if (!(name in tracked)) missing.push(name)
  }
  for (const [name, entry] of Object.entries(tracked)) {
    if (entry.level !== 'draft' && !names.has(name)) stale.push(name)
  }
  missing.sort()
  stale.sort()
  return { kind, missing, stale }
}

/** Category names in maturity.json insertion order, entries sorted per category. */
function grouped (tracked: Section): Map<string, [string, Entry][]> {
  const groups = new Map<string, [string, Entry][]>()
  for (const [name, entry] of Object.entries(tracked)) {
    const group = groups.get(entry.category) ?? []
    group.push([name, entry])
    groups.set(entry.category, group)
  }
  for (const group of groups.values()) {
    group.sort(([a], [b]) => a.localeCompare(b))
  }
  return groups
}

function counts (maturity: Maturity, components: number, composables: number, utilityCount: number): string {
  const categories = new Set<string>()
  for (const section of [maturity.composables, maturity.components, maturity.utilities]) {
    for (const entry of Object.values(section)) {
      categories.add(entry.category)
    }
  }
  return `**${components} components, ${composables} composables, ${utilityCount} utilities** across ${categories.size} categories. Compound-component APIs with WAI-ARIA semantics.`
}

/**
 * Exported components grouped by category. Draft entries are unshipped, so
 * they are quarantined under an explicit "do not import" heading instead of
 * being presented as available.
 */
function list (tracked: Section): string {
  const lines = ['**Available components:**', '']
  const planned: string[] = []
  for (const [category, group] of grouped(tracked)) {
    const names: string[] = []
    for (const [name, entry] of group) {
      if (entry.level === 'draft') {
        planned.push(`\`${name}\``)
      } else {
        names.push(`\`${name}\`${mark(entry.level)}`)
      }
    }
    if (names.length > 0) {
      lines.push(`- *${capitalize(category)}:* ${names.join(', ')}`)
    }
  }
  if (planned.length > 0) {
    planned.sort()
    lines.push('', '**Planned (not yet exported — do not import):**', '', `- ${planned.join(', ')}`)
  }
  return lines.join('\n')
}

function surface (maturity: Maturity, glosses: Map<string, string | undefined>): string {
  const lines = [
    '## Full API surface',
    '',
    'Every public composable and utility, grouped by category. `(stable)` and `(draft)` are marked; unmarked entries are preview.',
  ]
  for (const [title, section] of [['Composables', maturity.composables], ['Utilities', maturity.utilities]] as const) {
    lines.push('', `### ${title}`)
    for (const [category, group] of grouped(section)) {
      lines.push('', `**${capitalize(category)}:**`, '')
      for (const [name, entry] of group) {
        const gloss = glosses.get(name)
        lines.push(`- \`${name}\`${gloss ? ` — ${gloss}` : ''}${mark(entry.level)}`)
      }
    }
  }
  return lines.join('\n')
}

/** Index of a marker that must occur exactly once, or a named hard error. */
function position (content: string, marker: string, name: string): number {
  const first = content.indexOf(marker)
  if (first === -1) {
    throw new Error(`skills/vuetify0/SKILL.md is missing the "${name}" marker: ${marker}`)
  }
  if (content.lastIndexOf(marker) !== first) {
    throw new Error(`skills/vuetify0/SKILL.md has duplicate "${name}" markers: ${marker}`)
  }
  return first
}

function inject (content: string, name: string, body: string): string {
  const open = `<!-- @generated:${name} -->`
  const close = `<!-- @generated:${name}:end -->`
  const start = position(content, open, name)
  const end = position(content, close, name)
  if (end < start) {
    throw new Error(`skills/vuetify0/SKILL.md has inverted "${name}" markers: ${close} appears before ${open}`)
  }
  return `${content.slice(0, start + open.length)}\n${NOTICE}\n${body}\n${content.slice(end)}`
}

async function main (): Promise<void> {
  const check = process.argv.includes('--check')
  const maturity = JSON.parse(await readFile(resolve(SRC, 'maturity.json'), 'utf8')) as Maturity
  const composables = (await barrel(resolve(SRC, 'composables/index.ts'))).map(entry => entry.name)
  const components = (await barrel(resolve(SRC, 'components/index.ts'))).map(entry => entry.name)
  const modules = await utilities()

  const mismatches = [
    validate('composables', composables, maturity.composables),
    validate('components', components, maturity.components),
    validate('utilities', modules.keys(), maturity.utilities),
  ].filter(result => result.missing.length || result.stale.length)

  if (mismatches.length > 0) {
    console.error('maturity.json and the export surface disagree — fix the data, never this script:\n')
    for (const { kind, missing, stale } of mismatches) {
      for (const name of missing) {
        console.error(`  ${kind}: "${name}" is exported but has no maturity.json entry`)
      }
      for (const name of stale) {
        console.error(`  ${kind}: "${name}" is in maturity.json (non-draft) but is not exported`)
      }
    }
    process.exitCode = 1
    return
  }

  const glosses = new Map<string, string | undefined>()
  for (const [name, entry] of Object.entries(maturity.composables)) {
    glosses.set(name, await composableGloss(name, entry))
  }
  for (const [name, entry] of Object.entries(maturity.utilities)) {
    glosses.set(name, utilityGloss(name, entry, modules))
  }

  const current = await readFile(SKILL, 'utf8')
  let content = current
  content = inject(content, 'counts', counts(maturity, components.length, composables.length, modules.size))
  content = inject(content, 'components', list(maturity.components))
  content = inject(content, 'api', surface(maturity, glosses))

  if (check) {
    if (content !== current) {
      console.error('skills/vuetify0/SKILL.md is out of date — run `pnpm skill` to regenerate')
      process.exitCode = 1
    }
    return
  }

  if (content === current) {
    console.log('skills/vuetify0/SKILL.md already up to date')
  } else {
    await writeFile(SKILL, content)
    console.log(`Wrote ${SKILL}`)
  }
  console.log(`${components.length} components, ${composables.length} composables, ${modules.size} utilities`)
}

await main()
