/**
 * Prebake dist/theme.css for zero-config install:
 *   import '@paper/onyx/theme.css'
 *
 * Renders the same shared emitters (`foundations()`, `block()` from
 * `src/css.ts`) the runtime `OnyxStyleSheetAdapter` uses — this is a
 * rendering of those emitters, never a re-implementation. Self-contained (no
 * @vuetify/v0 import anywhere in this script's import graph) so it runs
 * after tsdown without requiring packages/0's dist to be built first.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { themes } from '../src/colors'
import { block, contrastMore, foundations } from '../src/css'

const here = dirname(fileURLToPath(import.meta.url))
const out = resolve(here, '../dist/theme.css')
const banner = '/* @paper/onyx — prebaked default theme. Generated by scripts/bake-theme.ts. Do not edit. */\n'

// Iterates the themes record itself — name + dark flag — instead of hand-enumerating
// onyx/onyx-light, so a future third theme gets baked automatically rather than
// silently missing this file. :root stays keyed to whichever entry is flagged
// `dark: true` (the zero-config default per SPEC.md, "Onyx is dark by default"),
// not to a hardcoded 'onyx' lookup.
let defaultDark: Record<string, string> | undefined
let css = banner + foundations()

for (const [name, theme] of Object.entries(themes)) {
  css += block(`[data-theme="${name}"]`, theme.colors, theme.dark)
  if (theme.dark) defaultDark = theme.colors
}

if (!defaultDark) {
  throw new Error('[bake-theme] no theme in colors.ts\'s `themes` record is flagged `dark: true` — :root has nothing to bake against.')
}

css += block(':root', defaultDark, true) + contrastMore()

mkdirSync(dirname(out), { recursive: true })
writeFileSync(out, css)
console.log(`[bake-theme] wrote ${out} (${css.length} bytes)`)
