/**
 * Prebake dist/theme.css for zero-config install:
 *   import '@paper/onyx/theme.css'
 *
 * Renders the same shared emitters (`foundations()`, `block()` from
 * `src/css.ts`) the runtime `OnyxStyleSheetAdapter` uses — this is a
 * rendering of those emitters, never a re-implementation. Self-contained (no
 * @vuetify/v0 import anywhere in this script's import graph) so it runs
 * after tsdown without requiring packages/0's dist to be built first.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { themes } from '../src/colors'
import { block, foundations } from '../src/css'

const here = dirname(fileURLToPath(import.meta.url))
const out = resolve(here, '../dist/theme.css')
const banner = '/* @paper/onyx — prebaked default theme. Generated by scripts/bake-theme.ts. Do not edit. */\n'

const dark = themes.onyx.colors
const light = themes['onyx-light'].colors

const css = banner
  + foundations()
  + block('[data-theme="onyx"]', dark, true)
  + block('[data-theme="onyx-light"]', light)
  + block(':root', dark, true)

mkdirSync(dirname(out), { recursive: true })
writeFileSync(out, css)
console.log(`[bake-theme] wrote ${out} (${css.length} bytes)`)
