/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    V0Paper: typeof import('./components/V0Paper/V0Paper.vue')['default']
    VButton: typeof import('./components/VButton/VButton.vue')['default']
  }
}
