/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    V0Affix: typeof import('./components/V0Affix/V0Affix.vue')['default']
    V0Avatar: typeof import('./components/V0Avatar/V0Avatar.vue')['default']
    V0Button: typeof import('./components/V0Button/V0Button.vue')['default']
    V0Icon: typeof import('./components/V0Icon/V0Icon.vue')['default']
    V0Img: typeof import('./components/V0Img/V0Img.vue')['default']
    V0Paper: typeof import('./components/V0Paper/V0Paper.vue')['default']
  }
}
