import { describe, expect, expectTypeOf, it } from 'vitest'

import * as Components from '#v0/components'
import * as Composables from '#v0/composables'
import * as Types from '#v0/types'

// Utilities
import * as Utilities from '#v0/utilities'

// Types
import type {
  Activation,
  DeepPartial,
  DOMElement,
  Extensible,
  ID,
  MaybeArray,
  UnknownObject,
  V0ErrorCode,
  V0ErrorDetails,
} from '#v0/types'

/**
 * Public-surface freeze guard.
 *
 * Asserts the sorted list of runtime exports from each public barrel matches a
 * committed inline array. Any add / remove / rename of a public export turns
 * into a reviewable +/- diff in this file, so accidental surface changes can't
 * slip through unnoticed.
 *
 * Inline `toEqual(EXPECTED)` is used over `toMatchSnapshot()` deliberately: a
 * committed array cannot be silently regenerated by `vitest -u`, so changing
 * the public surface forces a conscious edit here — which is the whole point of
 * an API freeze. A `__snapshots__` file (or `toMatchInlineSnapshot`) would let
 * a drive-by `-u` rubber-stamp the change.
 */

const COMPOSABLES = [
  'ClientComboboxAdapter', 'ClientDataTableAdapter', 'ComboboxAdapter', 'ConsolaLoggerAdapter', 'DataTableAdapter', 'DateAdapter', 'DragDropAdapter', 'FeaturesAdapter', 'KeyboardAdapter', 'LocaleAdapter', 'LoggerAdapter', 'MemoryStorageAdapter', 'PermissionsAdapter', 'PinoLoggerAdapter', 'PointerAdapter', 'ReducedMotionAdapter', 'RtlAdapter', 'ServerComboboxAdapter', 'ServerDataTableAdapter', 'ServerGridAdapter', 'StorageAdapter', 'ThemeAdapter', 'V0LocaleAdapter', 'V0LoggerAdapter', 'V0ReducedMotionAdapter', 'V0RtlAdapter', 'V0StyleSheetThemeAdapter', 'V0UnheadThemeAdapter', 'VirtualDataTableAdapter', 'computeDepth', 'createBreadcrumbs', 'createBreadcrumbsContext', 'createBreakpoints', 'createBreakpointsContext', 'createBreakpointsPlugin', 'createCombobox', 'createComboboxContext', 'createContext', 'createDataGrid', 'createDataGridContext', 'createDataTable', 'createDataTableContext', 'createDate', 'createDateContext', 'createDatePlugin', 'createFallbackHydration', 'createFeatures', 'createFeaturesContext', 'createFeaturesPlugin', 'createFilter', 'createFilterContext', 'createForm', 'createFormContext', 'createGroup', 'createGroupContext', 'createHydration', 'createHydrationContext', 'createHydrationPlugin', 'createInput', 'createKanban', 'createLocale', 'createLocaleContext', 'createLocaleFallback', 'createLocalePlugin', 'createLogger', 'createLoggerContext', 'createLoggerPlugin', 'createModel', 'createNested', 'createNestedContext', 'createNotifications', 'createNotificationsContext', 'createNotificationsPlugin', 'createNumberField', 'createNumeric', 'createOtp', 'createOverflow', 'createOverflowContext', 'createPagination', 'createPaginationContext', 'createPermissions', 'createPermissionsContext', 'createPermissionsPlugin', 'createPlugin', 'createPluginContext', 'createProgress', 'createProgressContext', 'createQueue', 'createQueueContext', 'createRating', 'createRatingContext', 'createReducedMotion', 'createReducedMotionContext', 'createReducedMotionPlugin', 'createRegistry', 'createRegistryContext', 'createRtl', 'createRtlContext', 'createRtlFallback', 'createRtlPlugin', 'createRules', 'createRulesContext', 'createRulesFallback', 'createRulesPlugin', 'createSelection', 'createSelectionContext', 'createSingle', 'createSingleContext', 'createSlider', 'createSortable', 'createStack', 'createStackContext', 'createStackPlugin', 'createStep', 'createStepContext', 'createStorage', 'createStorageContext', 'createStoragePlugin', 'createTheme', 'createThemeContext', 'createThemePlugin', 'createTimeline', 'createTimelineContext', 'createTokens', 'createTokensContext', 'createTooltipContext', 'createTooltipFallback', 'createTooltipPlugin', 'createTrinity', 'createValidation', 'createVirtual', 'createVirtualContext', 'extractLeaves', 'flatten', 'isStandardSchema', 'provideContext', 'resolveHeaders', 'toArray', 'toElement', 'toHighlight', 'toReactive', 'useBreadcrumbs', 'useBreakpoints', 'useClickOutside', 'useCombobox', 'useContext', 'useDataGrid', 'useDataTable', 'useDate', 'useDelay', 'useDocumentEventListener', 'useDragDrop', 'useElementIntersection', 'useElementSize', 'useEventListener', 'useFeatures', 'useFilter', 'useForm', 'useGroup', 'useHotkey', 'useHydration', 'useImage', 'useIntersectionObserver', 'useLazy', 'useLocale', 'useLogger', 'useMediaQuery', 'useMutationObserver', 'useNested', 'useNotifications', 'useOverflow', 'usePagination', 'usePermissions', 'usePopover', 'usePrefersContrast', 'usePrefersDark', 'usePrefersReducedMotion', 'usePresence', 'useProgress', 'useProxyModel', 'useProxyRegistry', 'useQueue', 'useRaf', 'useRating', 'useReducedMotion', 'useRegistry', 'useResizeObserver', 'useRovingFocus', 'useRtl', 'useRules', 'useSelection', 'useSingle', 'useStack', 'useStep', 'useStorage', 'useTheme', 'useTimeline', 'useTimer', 'useToggleScope', 'useTokens', 'useTooltip', 'useVirtual', 'useVirtualFocus', 'useWindowEventListener',
]

const COMPONENTS = [
  'Alert', 'AlertDescription', 'AlertDialog', 'AlertDialogAction', 'AlertDialogActivator', 'AlertDialogCancel', 'AlertDialogClose', 'AlertDialogContent', 'AlertDialogDescription', 'AlertDialogRoot', 'AlertDialogTitle', 'AlertRoot', 'AlertTitle', 'AspectRatio', 'Atom', 'Avatar', 'AvatarFallback', 'AvatarGroup', 'AvatarImage', 'AvatarIndicator', 'AvatarRoot', 'Breadcrumbs', 'BreadcrumbsDivider', 'BreadcrumbsEllipsis', 'BreadcrumbsItem', 'BreadcrumbsLink', 'BreadcrumbsList', 'BreadcrumbsPage', 'BreadcrumbsRoot', 'Button', 'ButtonContent', 'ButtonGroup', 'ButtonHiddenInput', 'ButtonIcon', 'ButtonLoading', 'ButtonRoot', 'Carousel', 'CarouselIndicator', 'CarouselItem', 'CarouselLiveRegion', 'CarouselNext', 'CarouselPrevious', 'CarouselProgress', 'CarouselRoot', 'CarouselViewport', 'Checkbox', 'CheckboxGroup', 'CheckboxHiddenInput', 'CheckboxIndicator', 'CheckboxRoot', 'CheckboxSelectAll', 'Collapsible', 'CollapsibleActivator', 'CollapsibleContent', 'CollapsibleCue', 'CollapsibleRoot', 'Combobox', 'ComboboxActivator', 'ComboboxContent', 'ComboboxControl', 'ComboboxCue', 'ComboboxDescription', 'ComboboxEmpty', 'ComboboxError', 'ComboboxItem', 'ComboboxRoot', 'Dialog', 'DialogActivator', 'DialogClose', 'DialogContent', 'DialogDescription', 'DialogRoot', 'DialogTitle', 'ExpansionPanel', 'ExpansionPanelActivator', 'ExpansionPanelContent', 'ExpansionPanelCue', 'ExpansionPanelGroup', 'ExpansionPanelHeader', 'ExpansionPanelRoot', 'Form', 'Group', 'GroupItem', 'GroupRoot', 'Image', 'ImageFallback', 'ImageImg', 'ImagePlaceholder', 'ImageRoot', 'Input', 'InputControl', 'InputDescription', 'InputError', 'InputRoot', 'Locale', 'NumberField', 'NumberFieldControl', 'NumberFieldDecrement', 'NumberFieldDescription', 'NumberFieldError', 'NumberFieldIncrement', 'NumberFieldRoot', 'NumberFieldScrub', 'Overflow', 'OverflowIndicator', 'OverflowItem', 'OverflowRoot', 'Pagination', 'PaginationEllipsis', 'PaginationFirst', 'PaginationItem', 'PaginationLast', 'PaginationNext', 'PaginationPrev', 'PaginationRoot', 'PaginationStatus', 'Popover', 'PopoverActivator', 'PopoverContent', 'PopoverRoot', 'Portal', 'Presence', 'Progress', 'ProgressBuffer', 'ProgressFill', 'ProgressHiddenInput', 'ProgressLabel', 'ProgressRoot', 'ProgressTrack', 'ProgressValue', 'Radio', 'RadioGroup', 'RadioHiddenInput', 'RadioIndicator', 'RadioRoot', 'Rating', 'RatingHiddenInput', 'RatingItem', 'RatingRoot', 'Scrim', 'Select', 'SelectActivator', 'SelectContent', 'SelectCue', 'SelectItem', 'SelectPlaceholder', 'SelectRoot', 'SelectValue', 'Selection', 'SelectionItem', 'SelectionRoot', 'Single', 'SingleItem', 'SingleRoot', 'Slider', 'SliderHiddenInput', 'SliderRange', 'SliderRoot', 'SliderThumb', 'SliderTrack', 'Snackbar', 'SnackbarClose', 'SnackbarContent', 'SnackbarPortal', 'SnackbarQueue', 'SnackbarRoot', 'Splitter', 'SplitterHandle', 'SplitterPanel', 'SplitterRoot', 'Step', 'StepItem', 'StepRoot', 'Switch', 'SwitchGroup', 'SwitchHiddenInput', 'SwitchRoot', 'SwitchSelectAll', 'SwitchThumb', 'SwitchTrack', 'Tabs', 'TabsItem', 'TabsList', 'TabsPanel', 'TabsRoot', 'Theme', 'Toggle', 'ToggleGroup', 'ToggleIndicator', 'ToggleRoot', 'Tooltip', 'TooltipActivator', 'TooltipContent', 'TooltipRoot', 'Treeview', 'TreeviewActivator', 'TreeviewCheckbox', 'TreeviewContent', 'TreeviewCue', 'TreeviewGroup', 'TreeviewIndicator', 'TreeviewItem', 'TreeviewList', 'TreeviewRoot', 'TreeviewSelectAll', 'provideAlertDialogContext', 'provideAvatarGroup', 'provideAvatarRoot', 'provideBreadcrumbsRoot', 'provideButtonGroup', 'provideButtonRoot', 'provideCarouselRoot', 'provideCheckboxGroup', 'provideCheckboxRoot', 'provideCollapsible', 'provideComboboxContext', 'provideDialogContext', 'provideExpansionPanelGroup', 'provideExpansionPanelRoot', 'provideGroupRoot', 'provideImageRoot', 'provideInputRoot', 'provideNumberFieldRoot', 'provideOverflowRoot', 'providePaginationControls', 'providePaginationItems', 'providePaginationRoot', 'providePopoverContext', 'provideProgressRoot', 'provideRadioGroup', 'provideRadioRoot', 'provideRatingRoot', 'provideSelectContext', 'provideSelectionRoot', 'provideSingleRoot', 'provideSliderRoot', 'provideSnackbarQueueContext', 'provideSnackbarRootContext', 'provideSplitterRoot', 'provideStepRoot', 'provideSwitchGroup', 'provideSwitchRoot', 'provideTabsRoot', 'provideToggleGroup', 'provideToggleRoot', 'provideTooltipRoot', 'provideTreeviewItem', 'provideTreeviewList', 'provideTreeviewRoot', 'useAlertDialogContext', 'useAvatarGroup', 'useAvatarRoot', 'useBreadcrumbsRoot', 'useButtonGroup', 'useButtonRoot', 'useCarouselRoot', 'useCheckboxGroup', 'useCheckboxRoot', 'useCollapsible', 'useComboboxContext', 'useDialogContext', 'useExpansionPanelGroup', 'useExpansionPanelRoot', 'useGroupRoot', 'useImageRoot', 'useInputRoot', 'useNumberFieldRoot', 'useOverflowRoot', 'usePaginationControls', 'usePaginationItems', 'usePaginationRoot', 'usePopoverContext', 'useProgressRoot', 'useRadioGroup', 'useRadioRoot', 'useRatingRoot', 'useSelectContext', 'useSelectionRoot', 'useSingleRoot', 'useSliderRoot', 'useSnackbarQueueContext', 'useSnackbarRootContext', 'useSplitterRoot', 'useStepRoot', 'useSwitchGroup', 'useSwitchRoot', 'useTabsRoot', 'useToggleGroup', 'useToggleRoot', 'useTooltipRoot', 'useTreeviewItem', 'useTreeviewList', 'useTreeviewRoot',
]

const UTILITIES = [
  'UNSAFE_KEYS', 'V0Error', 'apca', 'clamp', 'foreground', 'hexToRgb', 'instanceExists', 'instanceName', 'isArray', 'isBoolean', 'isElement', 'isFunction', 'isNaN', 'isNull', 'isNullOrUndefined', 'isNumber', 'isObject', 'isPrimitive', 'isString', 'isSymbol', 'isThenable', 'isUndefined', 'isV0Error', 'mergeDeep', 'range', 'resolveIds', 'resolveIndexes', 'rgbToHex', 'useId',
]

describe('public surface', () => {
  it('should export the frozen set of composables', () => {
    expect(Object.keys(Composables).toSorted()).toEqual(COMPOSABLES)
  })

  it('should export the frozen set of components', () => {
    expect(Object.keys(Components).toSorted()).toEqual(COMPONENTS)
  })

  it('should export the frozen set of utilities', () => {
    expect(Object.keys(Utilities).toSorted()).toEqual(UTILITIES)
  })

  it('should export the frozen set of public types', () => {
    // The `#v0/types` barrel is type-only; its exports are erased at runtime,
    // so Object.keys() can't see them. The runtime assertion below pins the
    // barrel to zero runtime values (catching an accidental value export), and
    // each public type is referenced by name so removing or renaming one breaks
    // `pnpm typecheck` on this file. Additive type exports are non-breaking and
    // intentionally not caught.
    expect(Object.keys(Types)).toEqual([])
    expectTypeOf<Activation>().not.toBeNever()
    expectTypeOf<DeepPartial<{ a: number }>>().not.toBeNever()
    expectTypeOf<DOMElement>().not.toBeNever()
    expectTypeOf<Extensible<'a'>>().not.toBeNever()
    expectTypeOf<ID>().not.toBeNever()
    expectTypeOf<MaybeArray<string>>().not.toBeNever()
    expectTypeOf<UnknownObject>().not.toBeNever()
    expectTypeOf<V0ErrorCode>().not.toBeNever()
    expectTypeOf<V0ErrorDetails>().not.toBeNever()
  })
})
