/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCloseButton: typeof import('./components/app/AppCloseButton.vue')['default']
    AppIcon: typeof import('./components/app/AppIcon.vue')['default']
    AppIconButton: typeof import('./components/app/AppIconButton.vue')['default']
    AppLoaderIcon: typeof import('./components/app/AppLoaderIcon.vue')['default']
    AppSkeleton: typeof import('./components/app/AppSkeleton.vue')['default']
    AppThemeToggle: typeof import('./components/app/AppThemeToggle.vue')['default']
    PlaygroundApp: typeof import('./components/playground/app/PlaygroundApp.vue')['default']
    PlaygroundAppBar: typeof import('./components/playground/app/PlaygroundAppBar.vue')['default']
    PlaygroundAppContent: typeof import('./components/playground/app/PlaygroundAppContent.vue')['default']
    PlaygroundAppLeft: typeof import('./components/playground/app/PlaygroundAppLeft.vue')['default']
    PlaygroundAppRight: typeof import('./components/playground/app/PlaygroundAppRight.vue')['default']
    PlaygroundEditor: typeof import('./components/playground/editor/PlaygroundEditor.vue')['default']
    PlaygroundEditorBreadcrumbs: typeof import('./components/playground/editor/PlaygroundEditorBreadcrumbs.vue')['default']
    PlaygroundEditorFileTree: typeof import('./components/playground/editor/PlaygroundEditorFileTree.vue')['default']
    PlaygroundEditorPreview: typeof import('./components/playground/editor/PlaygroundEditorPreview.vue')['default']
    PlaygroundEditorTabs: typeof import('./components/playground/editor/PlaygroundEditorTabs.vue')['default']
    PlaygroundMarkdown: typeof import('./components/playground/markdown/PlaygroundMarkdown.vue')['default']
    PlaygroundMarkdownFooter: typeof import('./components/playground/markdown/PlaygroundMarkdownFooter.vue')['default']
    PlaygroundMarkdownHeader: typeof import('./components/playground/markdown/PlaygroundMarkdownHeader.vue')['default']
    PlaygroundSplitterHandle: typeof import('./components/playground/app/PlaygroundSplitterHandle.vue')['default']
    PlaygroundWorkspace: typeof import('./components/playground/workspace/PlaygroundWorkspace.vue')['default']
    PlaygroundWorkspaceBottom: typeof import('./components/playground/workspace/PlaygroundWorkspaceBottom.vue')['default']
    PlaygroundWorkspaceLeft: typeof import('./components/playground/workspace/PlaygroundWorkspaceLeft.vue')['default']
    PlaygroundWorkspaceRight: typeof import('./components/playground/workspace/PlaygroundWorkspaceRight.vue')['default']
    PlaygroundWorkspaceSide: typeof import('./components/playground/workspace/PlaygroundWorkspaceSide.vue')['default']
    PlaygroundWorkspaceTop: typeof import('./components/playground/workspace/PlaygroundWorkspaceTop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
