/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HxApiCardBadge: typeof import('./../src')['HxApiCardBadge']
    HxApiCardDefault: typeof import('./../src')['HxApiCardDefault']
    HxApiCardDescription: typeof import('./../src')['HxApiCardDescription']
    HxApiCardName: typeof import('./../src')['HxApiCardName']
    HxApiCardType: typeof import('./../src')['HxApiCardType']
    HxExampleCode: typeof import('./../src')['HxExampleCode']
    HxMermaidCaption: typeof import('./../src')['HxMermaidCaption']
    HxToc: typeof import('./../src')['HxToc']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
