name: Playground Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      packages: write
      deployments: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: vuetifyjs/setup-action@master
      - run: pnpm run build:play
      - uses: vuetifyjs/coolify-action@master
        with:
          imageName: v0-playground
          dockerfilePath: ./apps/playground/Dockerfile
          token: ${{ secrets.GITHUB_TOKEN  }}
          coolifyWebhook: ${{ secrets.COOLIFY_PLAYGROUND_WEBHOOK }}
          coolifySecret: ${{ secrets.COOLIFY_TOKEN }}
